import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.findTutors": "Find Tutors",
    "nav.conversationPartners": "Conversation Partners",
    "nav.forBusiness": "For Business",
    "nav.becomeTutor": "Become a Tutor",
    "nav.provenProgress": "Proven Progress",
    "nav.faq": "FAQ",
    "nav.login": "Log in",
    "nav.signup": "Sign up",
    "nav.profile": "Profile",
    "nav.dashboard": "Dashboard",
    "nav.schedule": "Schedule",
    "nav.lessonPlanner": "Lesson Planner",

    // Profile Settings
    "profile.settings.title": "Profile Settings",
    "profile.settings.desc": "Update your display name and profile picture.",
    "profile.settings.clickToUpload": "Click to upload a photo",
    "profile.settings.avatarUpdated": "Avatar updated!",
    "profile.settings.saved": "Profile saved!",
    "profile.settings.saving": "Saving...",
    "profile.settings.save": "Save Changes",
    "profile.settings.error": "Error",
    "profile.settings.imageOnly": "Please select an image file.",
    "profile.settings.fileTooLarge": "File must be under 2 MB.",
    "profile.settings.hourlyRate": "Hourly Rate ($)",
    "profile.settings.hourlyRatePlaceholder": "e.g. 25",
    "profile.settings.hourlyRateHint": "Set your price per hour in USD ($). This will be visible to students.",
    "profile.settings.account": "Account",
    "profile.settings.password": "Password",
    "profile.settings.emailSection": "Email",
    "profile.settings.localization": "Localization",
    "profile.settings.calendar": "Calendar",
    "profile.settings.notifications": "Notifications",
    "profile.settings.deleteAccount": "Delete account",
    "profile.settings.accountTitle": "Account Settings",
    "profile.settings.profileImage": "Profile image",
    "profile.settings.edit": "Edit",
    "profile.settings.uploadPhoto": "Upload photo",
    "profile.settings.maxFileSize": "Maximum size — 2MB",
    "profile.settings.fileFormats": "JPG or PNG format",
    "profile.settings.firstName": "First name",
    "profile.settings.lastName": "Last name",
    "profile.settings.accountEmail": "Email",
    "profile.settings.passwordTitle": "Change password",
    "profile.settings.passwordDesc": "Use your current password to confirm the change.",
    "profile.settings.currentPassword": "Current password",
    "profile.settings.newPassword": "New password",
    "profile.settings.confirmPassword": "Confirm password",
    "profile.settings.passwordSaved": "Password updated successfully!",
    "profile.settings.passwordMismatch": "Passwords do not match.",
    "profile.settings.invalidCurrentPassword": "Current password is incorrect.",
    "profile.settings.emailTitle": "Email",
    "profile.settings.emailDesc": "Your login email is managed here.",
    "profile.settings.localizationTitle": "Language, currency & timezone",
    "profile.settings.localizationDesc": "Choose how LearnEazy displays language, prices, and lesson times for your account.",
    "profile.settings.language": "Language",
    "profile.settings.currency": "Currency",
    "profile.settings.timezone": "Timezone",
    "profile.settings.localizationSaved": "Localization preferences saved!",
    "profile.settings.calendarTitle": "Google Calendar",
    "profile.settings.calendarDesc": "Calendar integration will be available soon.",
    "profile.settings.connectCalendar": "Connect Google Calendar",
    "profile.settings.notificationsTitle": "Notification Preferences",
    "profile.settings.notificationsDesc": "Manage how and when you hear from us.",
    "profile.settings.emailNotifications": "Email notifications",
    "profile.settings.transactionalTitle": "Transactional",
    "profile.settings.transactionalDesc": "Important updates about your account and activity.",
    "profile.settings.tipsTitle": "Tips and discounts",
    "profile.settings.tipsDesc": "Get learning resources and exclusive offers to support your progress.",
    "profile.settings.surveysTitle": "Surveys and interviews",
    "profile.settings.surveysDesc": "Take part in research studies to help us improve the student experience.",
    "profile.settings.notificationsSaved": "Notification preferences saved!",
    "profile.settings.deleteTitle": "Delete account",
    "profile.settings.deleteDesc": "Deleting your account is permanent and all your account information will be deleted along with it.",
    "profile.settings.deleteWarning": "Please type your email address to confirm account deletion.",
    "profile.settings.confirmEmail": "Confirm email",
    "profile.settings.confirmEmailPlaceholder": "Type your email address",
    "profile.settings.deleteButton": "Delete account",
    "profile.settings.deleteConfirmTitle": "Are you sure?",
    "profile.settings.deleteConfirmDesc": "This cannot be undone.",
    "profile.settings.accountDeleted": "Your account has been deleted.",
    "profile.settings.deleteFailed": "Unable to delete account.",

    // Hero
    "hero.badge": "Share your knowledge with our international community of students today!",
    "hero.title1": "Find the perfect",
    "hero.title2": "tutor for you",
    "hero.subtitle": "Connect with expert tutors in any subject. Personalized 1-on-1 lessons that fit your schedule and learning goals.",
    "hero.searchPlaceholder": "What do you want to learn?",
    "hero.search": "Search",
    "hero.nextLesson": "Next Lesson",
    "hero.nextLessonDesc": "Mathematics with Nino B.",
    "hero.joinNow": "Join Now",

    "brand.tagline": "Global Tutors. Personal Learning.",

    // Homepage
    "home.heroTitle": "Find the perfect tutor & start learning today",
    "home.heroCta": "Get started — it's free",
    "stats.tutors": "Experienced tutors",
    "stats.reviews": "5-star tutor reviews",
    "stats.subjects": "Subjects taught",
    "stats.nationalities": "Tutor nationalities",
    "stats.appRating": "on the App Store",
    "stats.lessons": "Lessons Completed",
    "stats.rating": "Average Rating",
    "home.teachers": "teachers",
    "home.cat.k12": "K-12 Subjects",
    "home.cat.gcse": "GCSE & A-Level",
    "home.cat.professional": "Professional Subjects",
    "home.subj.math": "Mathematics",
    "home.subj.english": "English Language & Literature",
    "home.subj.science": "Science (Biology, Chemistry, Physics)",
    "home.subj.biology": "Biology",
    "home.subj.physics": "Physics",
    "home.subj.chemistry": "Chemistry",
    "home.subj.history": "History & Geography",
    "home.subj.foreignLangs": "Foreign Languages",
    "home.subj.computerScience": "Computer Science",
    "home.subj.gcseCore": "All Core GCSE Subjects",
    "home.subj.aLevel": "A-Level Maths, Sciences, Economics & More",
    "home.subj.examPrep": "Exam Preparation & Revision",
    "home.subj.businessFinance": "Business & Finance",
    "home.subj.programming": "Programming & Software Development",
    "home.subj.dataScience": "Data Science & Analytics",
    "home.subj.marketing": "Marketing & Communications",
    "home.subj.law": "Law & Legal Studies",
    
    "home.subj.businessEnglish": "English for Professionals",
    "home.progressBadge": "Verified Results Platform",
    "home.progressTitle": "Real progress, measurable results, improved learning methods",
    "home.progressDesc": "LearnEazy helps you track your progress, reach your goals faster and more effectively.",
    "home.progressFeat1Title": "Progress Monitoring",
    "home.progressFeat1Desc": "Set goals with your tutor, measure your progress, and celebrate successful results together.",
    "home.progressFeat2Title": "Personalized Learning Paths",
    "home.progressFeat2Desc": "Personalized recommendations and curriculum adaptation based on your strengths.",
    "home.progressFeat3Title": "Guaranteed Results",
    "home.progressFeat3Desc": "If you don't see measurable progress in a short time, we'll match you with a new tutor — free of charge.",
    "home.howTitle": "How LearnEazy works:",
    "home.how1.title": "Find your tutor.",
    "home.how1.desc": "We'll connect you with the best qualified tutor that you choose yourself.",
    "home.how2.title": "Start learning.",
    "home.how2.desc": "Your tutor will deliver personalized teaching and tailor every lesson to your learning goals.",
    "home.how3.title": "Make progress every week.",
    "home.how3.desc": "Choose how many lessons you want, deepen your knowledge and achieve the results you desire!",
    "home.guaranteeTitle": "Lessons you'll love, with tutors who make learning easier.",
    "home.guaranteeDesc": "Try another tutor for free — you have the option to choose a second tutor at no cost.",
    "home.becomeTutorTitle": "Become a tutor",
    "home.becomeTutorDesc": "Share your knowledge with our international community of students. Register on LearnEazy.",
    "home.tutorBenefit1": "International students worldwide",
    "home.tutorBenefit2": "Grow your income",
    "home.tutorBenefit3": "Earn additional income securely",
    "home.becomeTutorBtn": "Become a tutor",
    "home.howPlatformWorks": "How our platform works",
    "home.corpTitle": "Language training for business",
    "home.corpDesc": "LearnEazy corporate training is designed for teams with personalized teaching methods.",
    "home.corpCta": "Book a demo",

    // How it works (legacy)
    "how.title": "How LearnEazy Works",
    "how.subtitle": "Start learning in 3 simple steps",
    "how.step1.title": "Find Your Tutor",
    "how.step1.desc": "Browse expert tutors by subject, price, and availability.",
    "how.step2.title": "Book a Lesson",
    "how.step2.desc": "Choose a time that works for you and book with one click.",
    "how.step3.title": "Start Learning",
    "how.step3.desc": "Join your AI-powered classroom and achieve your goals.",

    // CTA
    "cta.title": "Ready to start learning?",
    "cta.subtitle": "Join hundreds of students already learning with LearnEazy. Your first trial lesson is free.",
    "cta.button": "Find a Tutor",

    // Footer
    "footer.aboutUs": "About Us",
    "footer.forStudents": "For Students",
    "footer.forTutors": "For Tutors",
    "footer.subjects": "Subjects",
    "footer.howItWorks": "How it works",
    "footer.faq": "FAQ",
    "footer.forBusiness": "For Business",
    "footer.findTutor": "Find a Tutor",
    "footer.schoolSubjects": "School Subjects",
    "footer.examPrep": "Exam Preparation",
    "footer.programming": "Programming",
    "footer.art": "Drawing / Art",
    "footer.becomeTutor": "Become a Tutor",
    "footer.applyNow": "Apply Now",
    "footer.support": "Support",
    "footer.needHelp": "Need any help? Visit our FAQ",
    "footer.contacts": "Contacts",
    "footer.location": "1209 N Orange St, Wilmington, DE 19801",
    "footer.social": "Social",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.learn": "Learn",
    "footer.learnEnglish": "Learn English online",
    "footer.learnSpanish": "Learn Spanish online",
    "footer.learnFrench": "Learn French online",
    "footer.learnGerman": "Learn German online",
    "footer.learnItalian": "Learn Italian online",
    "footer.learnAnother": "Learn another language",
    "footer.onlineClasses": "Online Language Classes and Courses",
    "footer.onlineEnglishClasses": "Online English Classes",
    "footer.businessEnglish": "Business English Courses",
    "footer.onlineSpanishClasses": "Online Spanish Classes",
    "footer.onlineFrenchClasses": "Online French Classes",
    "footer.onlineGermanClasses": "Online German Classes",
    "footer.onlineChineseClasses": "Online Chinese Classes",
    
    "footer.onlineTurkishClasses": "Online Turkish Classes",
    "footer.onlinePortugueseClasses": "Online Portuguese Classes",
    "footer.oneOnOneTutors": "1-on-1 Tutors",
    "footer.englishTutors": "English Tutors",
    "footer.spanishTutors": "Spanish Tutors",
    "footer.frenchTutors": "French Tutors",
    "footer.germanTutors": "German Tutors",
    "footer.arabicTutors": "Arabic Tutors",
    
    "footer.chineseTutors": "Chinese Tutors",
    "footer.portugueseTutors": "Portuguese Tutors",
    "footer.mathTutors": "Math Tutors",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated",
    "privacy.section1.title": "1. Information We Collect",
    "privacy.section1.body": "We collect information you provide when creating an account, booking lessons, or contacting us. This includes your name, email address, profile information, and payment details. We also collect usage data such as pages visited, features used, and device information to improve our services.",
    "privacy.section2.title": "2. How We Use Your Information",
    "privacy.section2.body": "We use your information to provide and improve our tutoring services, process bookings and payments, communicate with you about lessons and account updates, personalize your learning experience, and ensure the safety and security of our platform.",
    "privacy.section3.title": "3. Information Sharing",
    "privacy.section3.body": "We share your information with tutors you book lessons with (name and lesson details), payment processors to complete transactions, and service providers who assist in operating our platform. We do not sell your personal information to third parties.",
    "privacy.section4.title": "4. Data Security",
    "privacy.section4.body": "We implement industry-standard security measures to protect your personal information, including encryption of data in transit and at rest, secure authentication, and regular security audits. However, no method of transmission over the internet is 100% secure.",
    "privacy.section5.title": "5. Your Rights",
    "privacy.section5.body": "You have the right to access, update, or delete your personal information at any time through your account settings. You may also request a copy of your data or ask us to restrict processing. To exercise these rights, contact us at support@learneazy.org.",
    "privacy.section6.title": "6. Contact Us",
    "privacy.section6.body": "If you have questions about this Privacy Policy, please contact us at support@learneazy.org or through our FAQ page.",

    // Cookie Policy
    "cookie.title": "Cookie Policy",
    "cookie.lastUpdated": "Last updated",
    "cookie.section1.title": "1. What Are Cookies",
    "cookie.section1.body": "Cookies are small text files that are placed on your device when you visit our website. They help us provide you with a better experience by remembering your preferences, analyzing site traffic, and enabling certain features.",
    "cookie.section2.title": "2. How We Use Cookies",
    "cookie.section2.body": "LearnEazy uses cookies for several purposes: to keep you signed in, to remember your language preference, to understand how you use our platform, and to improve our services. We also use cookies to deliver relevant content and measure the effectiveness of our communications.",
    "cookie.section3.title": "3. Types of Cookies We Use",
    "cookie.section3.body": "Essential cookies: Required for the website to function properly, including authentication and security. Functional cookies: Remember your preferences such as language and display settings. Analytics cookies: Help us understand how visitors interact with our website by collecting anonymous usage data. Marketing cookies: Used to deliver relevant advertisements and track campaign performance.",
    "cookie.section4.title": "4. Third-Party Cookies",
    "cookie.section4.body": "Some cookies are placed by third-party services that appear on our pages, such as analytics providers (e.g., Google Analytics) and social media platforms. These third parties may use cookies to collect information about your online activities across different websites.",
    "cookie.section5.title": "5. Managing Cookies",
    "cookie.section5.body": "You can control and manage cookies through your browser settings. Most browsers allow you to refuse or delete cookies. However, please note that disabling cookies may affect the functionality of our website and limit your ability to use certain features.",
    "cookie.section6.title": "6. Cookie Retention",
    "cookie.section6.body": "Session cookies are temporary and are deleted when you close your browser. Persistent cookies remain on your device for a set period or until you delete them. We retain analytics data in anonymized form for up to 26 months.",
    "cookie.section7.title": "7. Contact Us",
    "cookie.section7.body": "If you have questions about our use of cookies, please contact us at support@learneazy.org or visit our FAQ page.",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated",
    "terms.section1.title": "1. Acceptance of Terms",
    "terms.section1.body": "By accessing or using LearnEazy, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.",
    "terms.section2.title": "2. User Accounts",
    "terms.section2.body": "You must create an account to use certain features of our platform. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information during registration.",
    "terms.section3.title": "3. Bookings and Payments",
    "terms.section3.body": "When you book a lesson, you agree to pay the stated price. Cancellations must be made at least 24 hours before the scheduled lesson for a full refund. Late cancellations or no-shows may result in charges. Tutors set their own prices and LearnEazy facilitates the payment process.",
    "terms.section4.title": "4. Code of Conduct",
    "terms.section4.body": "Users must treat all members of the community with respect. Harassment, discrimination, or inappropriate behavior will not be tolerated and may result in account suspension or termination. Users may not use the platform for any illegal or unauthorized purpose.",
    "terms.section5.title": "5. Intellectual Property",
    "terms.section5.body": "All content on LearnEazy, including text, graphics, logos, and software, is the property of LearnEazy or its content suppliers. Lesson materials created by tutors remain their intellectual property unless otherwise agreed upon.",
    "terms.section6.title": "6. Limitation of Liability",
    "terms.section6.body": "LearnEazy provides a platform connecting students with tutors and is not responsible for the quality of instruction. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform.",
    "terms.section7.title": "7. Changes to Terms",
    "terms.section7.body": "We may update these Terms of Service from time to time. We will notify you of significant changes via email or through the platform. Continued use after changes constitutes acceptance of the new terms.",

    "search.all": "All",
    "search.placeholder": "Search tutors by name or subject...",
    "search.filters": "Filters",
    "search.subject": "Subject",
    "search.pricePerHour": "Price per hour ($)",
    "search.rating": "Rating",
    "search.availability": "Availability",
    "search.nativeSpeaker": "Native Speaker",
    "search.found": "found",
    "search.tutor": "tutor",
    "search.tutors": "tutors",
    "search.noResults": "No tutors found",
    "search.adjustFilters": "Try adjusting your filters",
    "search.native": "Native",

    // Tutor profile
    "profile.tutor": "Tutor",
    "profile.experience": "Experience",
    "profile.students": "Students",
    "profile.lessons": "Lessons",
    "profile.about": "About me",
    "profile.reviews": "Student Reviews",
    "profile.availableTimes": "Available Times",
    "profile.bookTrial": "Book Trial Lesson",
    "profile.sendMessage": "Send Message",
    "profile.freeTrial": "Free trial lesson",
    "profile.cancelAnytime": "Cancel anytime",
    "profile.aiClassroom": "AI-powered classroom",

    // Booking
    "booking.back": "Back to tutor profile",
    "booking.title": "Book Your Lesson",
    "booking.lessonDetails": "Lesson Details",
    "booking.date": "Date",
    "booking.time": "Time",
    "booking.total": "Total",
    "booking.trialTitle": "Book a trial lesson",
    "booking.trialDesc": "To discuss your level and learning plan",
    "booking.duration25": "25 mins",
    "booking.duration50": "50 mins",
    "booking.timezone": "In your time zone",
    "booking.morning": "Morning",
    "booking.afternoon": "Afternoon",
    "booking.evening": "Evening",
    "booking.continue": "Continue",
    "booking.selectTime": "Please select a time slot",
    "booking.yourTutor": "Your tutor",
    "booking.students": "students",
    "booking.lessons": "lessons",
    "booking.yearsTeaching": "years teaching",
    "booking.trialDetails": "Trial lesson details",
    "booking.timeBasedOnLocation": "Time is based on your location",
    "booking.cancelReschedule": "Cancel or reschedule for free until 11:00 on",
    "booking.checkoutInfo": "Checkout info",
    "booking.minLesson": "-min lesson",
    "booking.sslSecure": "Your information is secure and protected.",
    "booking.failed": "Booking failed",
    "booking.studentName": "Your Name",
    "booking.studentNamePlaceholder": "Enter your full name",
    "booking.studentEmail": "Your Email",
    "booking.studentEmailPlaceholder": "Enter your email address",
    "booking.studentPhone": "Phone Number",
    "booking.studentPhonePlaceholder": "Enter your phone number",
    "booking.notes": "Additional Notes",
    "booking.notesPlaceholder": "Any specific topics or goals for the lesson...",
    "booking.submitRequest": "Submit Booking Request",
    "booking.submitting": "Submitting...",
    "booking.thankYou": "Thank you for booking! We will review your request and send payment details to your email within 24 hours. Once payment is confirmed, your session will be scheduled.",
    "booking.thankYouTitle": "Booking Request Sent!",
    "booking.backHome": "Back to Home",
    "booking.viewTutors": "Find More Tutors",

    // Dashboard
    "dash.welcome": "Welcome back, Student!",
    "dash.overview": "Here's your learning overview",
    "dash.totalLessons": "Total Lessons",
    "dash.hoursLearned": "Hours Learned",
    "dash.thisWeek": "This Week",
    "dash.unread": "Unread",
    "dash.upcoming": "Upcoming Lessons",
    "dash.completed": "Completed Lessons",
    "dash.join": "Join",
    "dash.scheduled": "Scheduled",
    "dash.aiInsights": "AI Insights",
    "dash.recentActivity": "Recent Activity",
    "dash.findMore": "Find More Tutors",
    "dash.aiPractice": "AI Practice",

    // AI Practice
    "ai.title": "AI Practice",
    "ai.subtitle": "Daily exercises and scenario practice powered by AI",
    "ai.daily": "Daily Exercises",
    "ai.completed": "completed",
    "ai.startExercise": "Start Exercise with AI",
    "ai.scenario": "Scenario Practice",

    // Classroom
    "class.liveSession": "Live Session",
    "class.video": "Video",
    "class.materials": "Materials",
    "class.chat": "Chat",
    "class.notes": "Notes",
    "class.lessonNotes": "Lesson Notes",
    "class.typePlaceholder": "Type your message...",
    "class.notesPlaceholder": "Take notes here...",

    // Messages
    "msg.search": "Search messages...",
    "msg.typePlaceholder": "Type a message...",
    "msg.send": "Send message",
    "msg.attach": "Attach file",
    "msg.emoji": "Open emoji picker",
    "msg.removeAttachment": "Remove attachment",
    "msg.deleteConversation": "Delete conversation",
    "msg.deleteConversationDesc": "Are you sure you want to delete this conversation? This action cannot be undone.",
    "msg.cancel": "Cancel",
    "msg.delete": "Delete",
    "msg.messageSent": "Message sent",
    "msg.messageFailed": "Unable to send message",
    "msg.attachmentFailed": "Unable to upload attachment",
    "msg.attachmentTooLarge": "Attachment must be under 10 MB.",
    "msg.deleted": "Conversation deleted",
    "msg.deleteFailed": "Unable to delete conversation",
    "msg.file": "Attachment",
    "msg.emptyComposer": "Write a message or attach a file.",
    "msg.markedRead": "Marked as read",

    // For Business
    "biz.title": "LearnEazy for Business",
    "biz.subtitle": "Upskill your team with personalized tutoring and AI-powered learning tools.",
    "biz.cta": "Send Enquiry",
    "biz.ctaSub": "Free consultation · No commitment",
    "biz.whyTitle": "Why Companies Choose LearnEazy",
    "biz.feat1.title": "Tailored Training Programs",
    "biz.feat1.desc": "Custom curricula designed around your team's skill gaps and business objectives. From language training to technical upskilling.",
    "biz.feat2.title": "Progress Tracking & Analytics",
    "biz.feat2.desc": "Real-time dashboards showing team progress, engagement metrics, and ROI on your training investment.",
    "biz.feat3.title": "Flexible Scheduling",
    "biz.feat3.desc": "Lessons that fit around your team's work schedule. Morning, evening, and weekend availability.",
    "biz.feat4.title": "AI-Powered Practice",
    "biz.feat4.desc": "Between tutor sessions, your team continues learning with AI exercises tailored to their level and goals.",
    "biz.feat5.title": "Dedicated Account Manager",
    "biz.feat5.desc": "A single point of contact to manage onboarding, scheduling, and reporting for your entire team.",
    "biz.feat6.title": "Volume Discounts",
    "biz.feat6.desc": "Competitive pricing for teams of all sizes. The more seats, the better the rate.",
    "biz.statsTitle": "Trusted by Leading Companies",
    "biz.stat1": "Corporate Clients",
    "biz.stat2": "Employees Trained",
    "biz.stat3": "Average Satisfaction",
    "biz.stat4": "Languages Taught",
    "biz.useCases": "Popular Use Cases",
    "biz.use1.title": "Language Training",
    "biz.use1.desc": "English, Spanish, French and more — prepare your team for international business.",
    "biz.use2.title": "Tech Upskilling",
    "biz.use2.desc": "Python, JavaScript, data science — keep your engineering team ahead of the curve.",
    "biz.use3.title": "Onboarding Programs",
    "biz.use3.desc": "Accelerate new hire productivity with structured learning paths and mentoring.",
    "biz.contactTitle": "Ready to transform your team's skills?",
    "biz.contactSub": "Get a customized training plan tailored to your organization's needs.",
    "biz.contactBtn": "Get Started",
    "biz.form.company": "Company Name",
    "biz.form.name": "Contact Name",
    "biz.form.email": "Email",
    "biz.form.phone": "Phone",
    "biz.form.teamSize": "Team Size",
    "biz.form.teamSizePlaceholder": "e.g. 10-50 employees",
    "biz.form.message": "Message",
    "biz.form.messagePlaceholder": "Tell us about your training needs...",
    "biz.form.submit": "Send Inquiry",
    "biz.form.success": "Inquiry sent successfully! We'll be in touch soon.",
    "biz.form.error": "Something went wrong. Please try again.",

    // Become a Tutor
    "tutor.title": "Become a Tutor",
    "tutor.subtitle": "Share your expertise, set your own schedule, and earn on your terms.",
    "tutor.cta": "Create a tutor profile now",
    "tutor.ctaSub": "Free to join · Start earning in days",
    "tutor.whyTitle": "Why Teach on LearnEazy?",
    "tutor.feat1.title": "Set your own rate",
    "tutor.feat1.desc": "Choose your hourly rate and change it anytime. On average, English tutors charge $15-25 per hour.",
    "tutor.feat2.title": "Teach anytime, anywhere",
    "tutor.feat2.desc": "Decide when and how many hours you want to teach. No minimum time commitment or fixed schedule. Be your own boss!",
    "tutor.feat3.title": "Grow professionally",
    "tutor.feat3.desc": "Once you sign up and complete your application, you can be approved and start teaching in as little as three days.",
    "tutor.feat4.title": "Grow Your Brand",
    "tutor.feat4.desc": "Build your reputation with reviews, ratings, and a professional profile page.",
    "tutor.feat5.title": "Easy Payments",
    "tutor.feat5.desc": "Get paid reliably via bank transfer (IBAN). Simple and hassle-free.",
    "tutor.feat6.title": "Support & Community",
    "tutor.feat6.desc": "Access training resources, teaching tips, and a community of fellow tutors.",
    "tutor.howTitle": "How It Works",
    "tutor.step1.title": "Sign up",
    "tutor.step1.desc": "to create your tutor profile",
    "tutor.step2.title": "Get approved",
    "tutor.step2.desc": "by our team in 5 business days",
    "tutor.step3.title": "Start earning",
    "tutor.step3.desc": "by teaching students all over the world!",
    "tutor.statsTitle": "Join Our Growing Community",
    "tutor.stat1": "Active Tutors",
    "tutor.stat2": "Avg. Monthly Earnings",
    "tutor.stat3": "Tutor Satisfaction",
    "tutor.stat4": "Subjects Available",
    "tutor.reqTitle": "What We Look For",
    "tutor.req1": "Expertise in your subject area",
    "tutor.req2": "Strong communication skills",
    "tutor.req3": "Reliable internet connection",
    "tutor.req4": "Passion for helping students learn",
    "tutor.req5": "Minimum 2 years of teaching or professional experience",
    "tutor.readyTitle": "Get paid to teach online",
    "tutor.readySub": "Connect with thousands of learners around the world and teach from your living room.",
    "tutor.readyBtn": "Create a tutor profile now",
    "tutor.heroHeadline": "Make a living by teaching the largest community of learners worldwide",
    "tutor.teachStudentsTitle": "Teach students from over 180 countries",
    "tutor.teachStudentsDesc": "LearnEazy tutors teach 800,000+ students globally. Join us and you'll have everything you need to teach successfully.",
    "tutor.pf1": "Steady stream of new students",
    "tutor.pf2": "Smart calendar",
    "tutor.pf3": "Interactive classroom",
    "tutor.pf4": "Easy bank transfer payments",
    "tutor.pf5": "Professional development webinars",
    "tutor.pf6": "Supportive tutor community",
    "tutor.testimonialQuote": "LearnEazy allowed me to make a living without leaving home!",
    "tutor.testimonialAuthor": "Krista A. · English tutor",
    "tutor.faqTitle": "Frequently asked questions",
    "tutor.faq1.q": "What kind of tutors does LearnEazy look for?",
    "tutor.faq1.a": "No specific certification or teaching experience is required! We welcome tutors who:\n\n• Enjoy sharing knowledge and making a difference in students' lives\n• Have outstanding communication skills\n• Are willing to provide a personalized learning experience to international students",
    "tutor.faq2.q": "What subject can I teach?",
    "tutor.faq2.a": "We have over 100 subjects on LearnEazy, including languages, school and university subjects, hobbies and art.",
    "tutor.faq3.q": "How do I become an online tutor at LearnEazy?",
    "tutor.faq3.a": "1. Provide some basic information about yourself\n2. Upload your headshot photo\n3. Describe your strengths as a tutor\n4. Record a short video introduction (up to 2 mins long)\n5. Choose your availability\n\nYou'll see tips and examples at each step of the registration process to help you create a great tutor profile. When you complete registration, our Tutor Success team will review your profile within 5 business days. Once your profile is approved, students from around the world will see it on LearnEazy and will be able to book lessons with you.",
    "tutor.faq4.q": "How can I get my profile approved quickly?",
    "tutor.faq4.a": "Sometimes, we don't approve tutor profiles at the first attempt because the profile photo, video or description doesn't meet our requirements. Make sure you use a real photo of yourself, take the time to record a short video and describe your strengths as a tutor in the description. A surefire way to get approved is to follow the tips given at each step of the registration process.\n\nAlso, be sure to avoid mentioning any contact details, lesson prices or misleading information in your profile description and video.",
    "tutor.faq5.q": "Why should I teach on LearnEazy?",
    "tutor.faq5.a": "Because it's easy and flexible! If you teach with LearnEazy, you:\n\n• Earn by sharing what you know\n• Get a steady stream of new students looking to learn online\n• Manage your lessons and connect with students easily\n• Teach whenever and wherever you want\n• Get paid easily via bank transfer\n• Get support from our friendly team through professional development webinars, live chat and email\n• Join a community of expert tutors who are always there for you\n\n...and more to come! We're constantly improving the platform and teaching tools for our tutors based on their needs.",
    "tutor.faq6.q": "What computer equipment do I need to teach on LearnEazy?",
    "tutor.faq6.a": "You will need a laptop or a desktop computer, a stable internet connection, a webcam, and a microphone for conducting lessons in the LearnEazy virtual classroom.",
    "tutor.faq7.q": "Is it free to create a tutor profile on LearnEazy?",
    "tutor.faq7.a": "Yes. It is free to create a tutor profile, get exposure to students, and use LearnEazy's tools and materials. We only charge a commission for the lessons that you have taught.",
    "tutor.faq8.q": "How much can I earn on LearnEazy?",
    "tutor.faq8.a": "Most popular tutors on LearnEazy earn up to $550 a week. Your earnings depend on the hourly rate you set, the number of lessons you teach and how many students continue learning with you after the trial lesson. A tip for newly registered tutors: start with a lower hourly rate to get first students faster. You can change your rate anytime.",
    // Tutor Application Portal
    "tutor.apply.step": "Step",
    "tutor.apply.step1Title": "Personal Information",
    "tutor.apply.step1Desc": "Tell us about yourself so we can get to know you.",
    "tutor.apply.step2Title": "Qualifications & Experience",
    "tutor.apply.step2Desc": "Share your teaching background and credentials.",
    "tutor.apply.step3Title": "Subjects & Rates",
    "tutor.apply.step3Desc": "Choose what you want to teach and set your price.",
    "tutor.apply.step4Title": "Availability & Final Details",
    "tutor.apply.step4Desc": "Let us know when you can teach and confirm your application.",
    "tutor.apply.firstName": "First Name",
    "tutor.apply.lastName": "Last Name",
    "tutor.apply.email": "Email",
    "tutor.apply.phone": "Phone",
    "tutor.apply.country": "Country",
    "tutor.apply.experience": "Teaching Experience",
    "tutor.apply.selectExp": "Select experience level",
    "tutor.apply.education": "Education",
    "tutor.apply.educationPlaceholder": "e.g. Master's in Education, King's College London",
    "tutor.apply.certifications": "Certifications",
    "tutor.apply.certPlaceholder": "e.g. TESOL, IELTS Certified",
    "tutor.apply.bio": "About You",
    "tutor.apply.bioPlaceholder": "Describe yourself, your teaching style, and what makes you a great tutor...",
    "tutor.apply.subjects": "Subjects You Teach",
    "tutor.apply.subj.english": "English",
    "tutor.apply.subj.mathematics": "Mathematics",
    "tutor.apply.subj.physics": "Physics",
    "tutor.apply.subj.chemistry": "Chemistry",
    "tutor.apply.subj.biology": "Biology",
    "tutor.apply.subj.history": "History",
    "tutor.apply.subj.geography": "Geography",
    "tutor.apply.subj.computerScience": "Computer Science",
    "tutor.apply.subj.business": "Business",
    "tutor.apply.subj.music": "Music",
    "tutor.apply.subj.nationalExams": "National Exams",
    "tutor.apply.subj.ielts": "IELTS",
    "tutor.apply.subj.toefl": "TOEFL",
    "tutor.apply.subj.french": "French",
    "tutor.apply.subj.german": "German",
    "tutor.apply.subj.spanish": "Spanish",
    
    "tutor.apply.subj.russian": "Russian",
    "tutor.apply.rate": "Hourly Rate",
    "tutor.apply.nativeLang": "Native Language",
    "tutor.apply.otherLangs": "Other Languages",
    "tutor.apply.availability": "Weekly Availability",
    "tutor.apply.selectAvail": "Select availability",
    "tutor.apply.availPartTime": "Part-time (1-15 hrs/week)",
    "tutor.apply.availFullTime": "Full-time (15-30 hrs/week)",
    "tutor.apply.availFlexible": "Flexible (30+ hrs/week)",
    "tutor.apply.timezone": "Timezone",
    "tutor.apply.selectTimezone": "Select timezone",
    "tutor.apply.aboutTeaching": "Your Teaching Philosophy",
    "tutor.apply.aboutTeachingPlaceholder": "Describe how you approach teaching and what students can expect...",
    "tutor.apply.terms": "I agree to the Terms of Service and confirm that the information provided is accurate.",
    "tutor.apply.back": "Back",
    "tutor.apply.next": "Continue",
    "tutor.apply.submit": "Submit Application",
    "tutor.apply.submitting": "Submitting...",
    "tutor.apply.error": "We couldn't submit your application. Please review your details and try again.",
    "tutor.apply.successTitle": "Application Submitted!",
    "tutor.apply.successDesc": "Thank you for applying! Our team will review your application within 24 hours and contact you via email.",
    "tutor.apply.backHome": "Back to Home",

    // Tutor Apply - Video
    "tutor.apply.videoLabel": "Introduction Video",
    "tutor.apply.videoDesc": "Record a 1-minute video about yourself and your teaching style. This is optional but highly encouraged — tutors with intro videos get up to 3x more bookings!",
    "tutor.apply.videoPlaceholder": "Paste a YouTube or Google Drive link to your video",
    "tutor.apply.videoTip": "Tip: Keep it short (under 2 min), speak clearly, and show your personality!",

    // Auth
    "auth.login": "Log in",
    "auth.loginDesc": "Welcome back! Sign in to your account.",
    "auth.signup": "Sign up",
    "auth.signupDesc": "Create your account to get started.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.displayName": "Display Name",
    "auth.displayNamePlaceholder": "Your name",
    "auth.forgotPassword": "Forgot password?",
    "auth.forgotDesc": "Enter your email and we'll send you a reset link.",
    "auth.sendResetLink": "Send reset link",
    "auth.sending": "Sending...",
    "auth.resetSent": "Check your email for the password reset link.",
    "auth.backToLogin": "Back to login",
    "auth.noAccount": "Don't have an account?",
    "auth.signupLink": "Sign up",
    "auth.hasAccount": "Already have an account?",
    "auth.loginLink": "Log in",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.error": "Error",
    "auth.welcomeBack": "Welcome back!",
    "auth.checkEmail": "Check your email",
    "auth.verifyEmail": "We sent you a verification link. Please check your email to confirm your account.",
    "auth.passwordMin": "Password must be at least 6 characters.",
    "auth.newPassword": "Set new password",
    "auth.newPasswordDesc": "Enter your new password below.",
    "auth.updatePassword": "Update password",
    "auth.updating": "Updating...",
    "auth.passwordUpdated": "Password updated successfully!",
    "auth.logout": "Log out",
    "auth.dashboard": "Dashboard",
    "auth.togglePassword": "Show or hide password",

    // Signup role selection
    "signup.chooseRole": "Join LearnEazy",
    "signup.chooseRoleDesc": "Choose how you'd like to use the platform",
    "signup.iAmStudent": "I am a Student",
    "signup.studentDesc": "Find tutors, book lessons, and start learning today.",
    "signup.signupAsStudent": "Sign up as Student",
    "signup.iAmTutor": "I am a Tutor",
    "signup.tutorDesc": "Share your knowledge and earn by teaching students.",
    "signup.applyAsTutor": "Apply as Tutor",
    "signup.studentTitle": "Create Student Account",
    "signup.studentSubtitle": "Sign up to book lessons and start learning.",
    "signup.createStudentAccount": "Create Account",

    // Booking flow
    "booking.subject": "Subject",
    "booking.duration": "Lesson Duration",
    "booking.selectDate": "Select a date",
    "booking.bookingWith": "Booking a lesson with",
    "booking.messageToTutor": "Message to Tutor (optional)",
    "booking.lessonWith": "lesson with",
    "booking.thankYouMsg": "Thank you for booking! Our team will contact you via chat within 24 hours to provide payment details and confirm your session.",
    "booking.loginRequired": "Create an account to book this lesson",
    "booking.loginRequiredDesc": "Sign up for free to complete your booking and track your lessons.",
    "booking.signupToBook": "Sign up to Book",
    "booking.viewLessons": "View My Lessons",

    // My Lessons
    "myLessons.title": "My Lessons",
    "myLessons.lessons": "Lessons",
    "myLessons.calendar": "Calendar",
    "myLessons.tutors": "Tutors",
    "myLessons.upcoming": "Upcoming Lessons",
    "myLessons.past": "Past Lessons",
    "myLessons.cancelled": "Cancelled",
    "myLessons.noUpcoming": "No upcoming lessons",
    "myLessons.scheduleNow": "Schedule your next lesson now!",
    "myLessons.scheduleLesson": "Schedule Lesson",
    "myLessons.joinMeet": "Join Google Meet",
    "myLessons.messageTutor": "Message tutor",
    "myLessons.cancel": "Cancel",
    "myLessons.cancelTitle": "Cancel this lesson?",
    "myLessons.cancelWarning": "Cancellations with less than 12 hours notice may be charged.",
    "myLessons.cancelReason": "Reason for canceling",
    "myLessons.cancelMessage": "Message (optional)",
    "myLessons.cancelMessagePlaceholder": "I need to cancel because...",
    "myLessons.cancelling": "Cancelling...",
    "myLessons.confirmCancel": "Confirm cancellation",
    "myLessons.lessonCancelled": "Lesson cancelled",
    "myLessons.scheduleNext": "Schedule your next lesson with {name}.",
    "myLessons.bookAgain": "Book Again",
    "myLessons.noTutors": "No tutors yet. Book a lesson to get started!",
    "myLessons.today": "Today",
    "myLessons.statusPending": "Pending",
    "myLessons.statusConfirmed": "Confirmed",
    "myLessons.statusCompleted": "Completed",
    "myLessons.statusCancelled": "Cancelled",
    "myLessons.cancelReason1": "This time doesn't work for me anymore",
    "myLessons.cancelReason2": "I have a technical issue",
    "myLessons.cancelReason3": "The tutor rescheduled to a time when I'm not available",
    "myLessons.cancelReason4": "The tutor asked me to cancel",
    "myLessons.cancelReason5": "I want to learn with a different tutor",
    "myLessons.cancelReason6": "I'm not ready to start learning yet",
    "myLessons.cancelReason7": "Other",
    "booking.duration30": "30 min",
    "booking.duration45": "45 min",
    "booking.duration60": "60 min",
    "booking.duration90": "90 min",
    "booking.fillRequired": "Please fill in all required fields.",

    // Admin
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Manage all bookings, payments, and lessons",
    "admin.totalBookings": "Total Bookings",
    "admin.pendingPayment": "Pending Payment",
    "admin.confirmed": "Confirmed",
    "admin.completedStat": "Completed",
    "admin.searchPlaceholder": "Search by student, tutor, or subject...",
    "admin.markPaid": "Mark as Paid",
    "admin.markCompleted": "Mark Completed",
    "admin.addMeetLink": "Add Google Meet Link",
    "admin.saveMeetLink": "Save Link",
    "admin.meetLinkSaved": "Google Meet link saved!",
    "admin.markedPaid": "Booking confirmed! Payment received.",
    "admin.noBookings": "No bookings yet",
    "admin.accessDenied": "Access Denied",
    "admin.adminOnly": "This page is only accessible to administrators.",
    "nav.admin": "Admin",
    "admin.bookingsTab": "Bookings",
    "admin.tutorAppsTab": "Tutor Applications",
    "admin.totalApps": "Total Applications",
    "admin.pendingApps": "Pending Review",
    "admin.approvedApps": "Approved",
    "admin.searchTutors": "Search by name, email, or subject...",
    "admin.approveTutor": "Approve",
    "admin.rejectTutor": "Reject",
    "admin.tutorApproved": "Tutor approved!",
    "admin.tutorRejected": "Tutor rejected.",
    "admin.noApps": "No tutor applications yet",
    "nav.tutorSchedule": "My Schedule",

    // Tutor Schedule
    "tutorSchedule.title": "My Schedule",
    "tutorSchedule.subtitle": "Your upcoming confirmed lessons with students",
    "tutorSchedule.upcomingCount": "Upcoming lessons",
    "tutorSchedule.daysScheduled": "Days scheduled",
    "tutorSchedule.totalTime": "Total teaching time",
    "tutorSchedule.earnedTotal": "Total earned (completed)",
    "tutorSchedule.upcomingRevenue": "Upcoming revenue",
    "tutorSchedule.calendarTitle": "Calendar",
    "tutorSchedule.calendarHint": "Pick a day to see the lessons booked there.",
    "tutorSchedule.allUpcomingTitle": "All upcoming lessons",
    "tutorSchedule.noLessons": "No upcoming lessons",
    "tutorSchedule.noLessonsDesc": "When students book lessons with you, they'll appear here.",
    "tutorSchedule.noLessonsOnDay": "No lessons on this day",
    "tutorSchedule.noLessonsOnDayDesc": "Choose another highlighted date to view booked lessons.",
    "tutorSchedule.joinMeet": "Join Meet",
    "tutorSchedule.noMeetLink": "Meet link pending",
    "tutorSchedule.unknownStudent": "Student",
    "tutorSchedule.setName": "Set your display name",
    "tutorSchedule.setNameDesc": "Please set your display name in Profile Settings to match the name used in bookings.",
    "tutorSchedule.loading": "Loading...",
    "tutorSchedule.todayPrefix": "Today,",
    "tutorSchedule.lessonSingle": "lesson",
    "tutorSchedule.lessonPlural": "lessons",
    "tutorSchedule.minutes": "min",
    "tutorSchedule.markComplete": "Mark Complete",
    "tutorSchedule.confirmCompleteTitle": "Mark Lesson as Complete?",
    "tutorSchedule.confirmCompleteDesc": "This will mark the lesson with {student} ({subject}) as completed and calculate your earnings automatically.",
    "tutorSchedule.confirmComplete": "Yes, Mark Complete",
    "tutorSchedule.completing": "Completing…",
    "tutorSchedule.cancel": "Cancel",
    "tutorSchedule.lessonCompleted": "Lesson completed",
    "tutorSchedule.lessonCompletedDesc": "Earnings have been calculated and added to your balance.",
    "tutorSchedule.error": "Error",

    // Tutor Profile page
    "tp.findTutors": "Find Tutors",
    "tp.tutorsOnline": "Tutors Online",
    "tp.tutorFrom": "tutor",
    "tp.from": "From",
    "tp.highlights": "Highlights",
    "tp.basedOnData": "Based on tutor data and real student reviews",
    "tp.superTutor": "Super Tutor",
    "tp.learnMore": "Learn more",
    "tp.teaches": "Teaches",
    "tp.aboutMe": "About me",
    "tp.iSpeak": "I speak",
    "tp.lessonRating": "Lesson rating",
    "tp.reassurance": "Reassurance",
    "tp.clarity": "Clarity",
    "tp.progress": "Progress",
    "tp.preparation": "Preparation",
    "tp.basedOnReviews": "Based on {count} anonymous student reviews",
    "tp.whatStudentsSay": "What my students say",
    "tp.basedOnStudentReviews": "Based on {count} student reviews",
    "tp.lessons": "lessons",
    "tp.edited": "(edited)",
    "tp.schedule": "Schedule",
    "tp.scheduleDesc": "Choose the time for your first lesson. The timings are displayed in your local timezone.",
    "tp.resume": "Resume",
    "tp.mySpecialties": "My specialties",
    "tp.youMightLike": "You might also like",
    "tp.perLesson": "/ lesson",
    "tp.bookTrialLesson": "Book trial lesson",
    "tp.sendMessage": "Send message",
    "tp.save": "Save",
    "tp.share": "Share",
    "tp.freeSwitch": "Free switch",
    "tp.freeSwitchDesc": "If {name} isn't a match, get 2 more free trials to find the right tutor.",
    "tp.reviews": "reviews",
    "tp.lesson": "lesson",

    // Dashboard
    "dash.welcomeBack": "Welcome back!",
    "dash.welcomeBackName": "Welcome back, {name}!",
    "dash.readyContinue": "Ready to continue learning with {name}?",
    "dash.subscribeContinue": "Subscribe to continue",
    "dash.continueLearning": "Continue learning",
    "dash.trialBooked": "Trial lesson booked",
    "dash.subscribe": "Subscribe",
    "dash.whatsNew": "What's new?",
    "dash.whatsNewName": "What's new, {name}?",
    "dash.findPerfect": "Find your perfect tutor",
    "dash.noLessonsYet": "No lessons yet",
    "dash.bookToStart": "Book a lesson with a tutor to get started",
    "dash.findTutor": "Find a tutor",
    "dash.goodToSee": "Good to see you, {name}!",
    "dash.nextLesson": "Your next lesson is coming up",
    "dash.joinLesson": "Join lesson",
    "dash.beforeLesson": "Before your lesson",
    "dash.shareLearning": "Share your learning needs",
    "dash.testClassroom": "Test your classroom",
    "dash.upNext": "Up next",
    "dash.withTutor": "with",
    "dash.perLesson": "per lesson",
    "dash.reviews0": "0 reviews",
    "tutorDashboard.portalLabel": "Tutor portal",
    "tutorDashboard.welcomeBack": "Welcome back, {name}",
    "tutorDashboard.heroDescription": "See today’s teaching snapshot, check your next lesson, and jump straight into your tutor tools.",
    "tutorDashboard.openSchedule": "Open schedule",
    "tutorDashboard.lessonPlanner": "Lesson planner",
    "tutorDashboard.today": "Today",
    "tutorDashboard.todayDescription": "Confirmed lessons on your calendar.",
    "tutorDashboard.upcoming": "Upcoming",
    "tutorDashboard.upcomingDescription": "Lessons currently booked ahead.",
    "tutorDashboard.earned": "Earned",
    "tutorDashboard.earnedDescription": "Revenue from completed lessons.",
    "tutorDashboard.nextLesson": "Next lesson",
    "tutorDashboard.loadingLessons": "Loading your upcoming lessons…",
    "tutorDashboard.viewFullSchedule": "View full schedule",
    "tutorDashboard.noUpcomingLessons": "No upcoming lessons yet.",
    "tutorDashboard.noUpcomingLessonsDescription": "Your next booking will appear here as soon as a student confirms a lesson.",
    "tutorDashboard.quickActions": "Quick actions",
    "tutorDashboard.manageSchedule": "Manage schedule",
    "tutorDashboard.buildLessonPlans": "Build lesson plans",
    "subscribe.title": "Choose your lesson plan",
    "subscribe.subtitle": "Pick a weekly package and our team will help you arrange the rest in chat.",
    "subscribe.package1": "1 lesson per week",
    "subscribe.package2": "2 lessons per week",
    "subscribe.package3": "3 lessons per week",
    "subscribe.package4": "4 lessons per week",
    "subscribe.package5": "5 lessons per week",
    "subscribe.popular": "Popular",
    "subscribe.lessonsPerMonth": "{count} lessons per month",
    "subscribe.pricePerLesson": "Price per lesson",
    "subscribe.totalMonthlyPrice": "Total monthly price",
    "subscribe.benefitsTitle": "Plan benefits",
    "subscribe.benefitSchedule": "Schedule lessons for any time",
    "subscribe.benefitTutor": "Change your tutor for free at any time",
    "subscribe.benefitCancel": "Cancel your plan at any time",
    "subscribe.benefitDuration": "Change lesson duration at any time",
    "subscribe.continue": "Continue",
    "subscribe.howPlansWork": "See how our plans work",
    "subscribe.faqTitle": "How our plans work",
    "subscribe.faqScheduleQ": "How to schedule your lessons",
    "subscribe.faqScheduleA": "Once you choose a plan, our team will contact you in chat and help arrange the lesson days and times that suit you.",
    "subscribe.faqTutorQ": "How to change your tutor",
    "subscribe.faqTutorA": "If you want a different tutor, send us a message in chat and we will help you switch at no extra charge.",
    "subscribe.faqCancelQ": "How to cancel your plan",
    "subscribe.faqCancelA": "If you need to stop, message our team in chat and we will help you cancel your plan at any time.",
    "subscribe.faqRenewalQ": "How to change your renewal date",
    "subscribe.faqRenewalA": "If you want a different renewal date, contact our team in chat and we will update it for you.",
    "subscribe.requestSentTitle": "Request received",
    "subscribe.requestSentMessage": "Our team will contact you via chat\nto arrange your subscription and\npayment details",
    "subscribe.close": "Close",
    "subscribe.rateHint": "Price per lesson is based on your tutor's current rate.",
    "subscribe.rateHintWithTutor": "Price per lesson is based on {name}'s current rate.",

    // Messages page
    "msg.home": "Home",
    "msg.messages": "Messages",
    "msg.myLessons": "My lessons",
    "msg.forBusiness": "For business",
    "msg.all": "All",
    "msg.unread": "Unread",
    "msg.archived": "Archived",
    "msg.noConversations": "No conversations yet",
    "msg.continueWith": "Continue learning with {name}.",
    "msg.noMessages": "No messages yet",
    "msg.tipReaction": "To add a reaction to a message, hover your cursor over it and click on the three dots icon",
    "msg.startConversation": "Start a conversation with {name}",
    "msg.yourMessage": "Your message",
    "msg.selectTutor": "Select a tutor to start a conversation",
    "msg.details": "Details",
    "msg.subscribe": "Subscribe",
    "msg.enterClassroom": "Enter classroom",

    // Search filters
    "search.any": "Any",
    "search.morning": "Morning",
    "search.afternoon": "Afternoon",
    "search.evening": "Evening",
    "search.perHour": "/hr",

    // Tutor data - subjects
    "td.math": "Mathematics",
    "td.physics": "Physics",
    "td.english": "English",
    "td.programming": "Programming",
    "td.chemistry": "Chemistry",
    "td.russian": "Russian",
    "td.music": "Music",
    // Tutor data - languages
    "td.lang.english": "English",
    "td.lang.russian": "Russian",
    // Tutor data - language levels
    "td.level.native": "Native",
    "td.level.upperIntB2": "Upper-Intermediate B2",
    // Tutor data - highlights
    "td.hl.patient": "Patient",
    "td.hl.structured": "Structured",
    "td.hl.goalFocused": "Goal-Focused",
    "td.hl.encouraging": "Encouraging",
    "td.hl.adaptable": "Adaptable",
    "td.hl.clear": "Clear",
    // Tutor data - specialties
    "td.spec.algebra": "Algebra",
    "td.spec.calculus": "Calculus",
    "td.spec.examPrep": "Exam Prep",
    "td.spec.mechanics": "Mechanics",
    "td.spec.thermodynamics": "Thermodynamics",
    "td.spec.ielts": "IELTS Prep",
    "td.spec.toefl": "TOEFL Prep",
    "td.spec.businessEng": "Business English",
    "td.spec.conversationalEng": "Conversational English",
    "td.spec.python": "Python",
    "td.spec.javascript": "JavaScript",
    "td.spec.react": "React",
    "td.spec.dataScience": "Data Science",
    // Tutor data - organizations & roles
    "td.org.learneazy": "LearnEazy",
    "td.org.university": "University",
    "td.org.freelance": "Freelance",
    "td.org.britishCouncil": "British Council",
    
    "td.role.seniorMathTutor": "Senior Mathematics Tutor",
    "td.role.teachingAssistant": "Teaching Assistant",
    "td.role.physicsTutor": "Physics Tutor",
    "td.role.phdResearcher": "PhD Researcher",
    "td.role.seniorEngTutor": "Senior English Tutor",
    "td.role.engInstructor": "English Instructor",
    "td.role.progTutor": "Programming Tutor",
    "td.role.softwareDev": "Software Developer",
    // Tutor data - responsiveness
    "td.responds1hr": "Usually responds in less than an hour",
    "td.responds2hr": "Usually responds within 2 hours",
    // Tutor data - schedule
    "td.scheduleRange": "Mar 14 – 20, 2026",
    // Tutor data - day names
    "td.day.sat": "Sat",
    "td.day.sun": "Sun",
    "td.day.mon": "Mon",
    "td.day.tue": "Tue",
    "td.day.wed": "Wed",
    "td.day.thu": "Thu",
    "td.day.fri": "Fri",
    // Tutor data - headlines & bios
    "td.nino.headline": "Expert Mathematics tutor with 10+ years helping students master algebra, calculus, and exam prep. Personalized approach for every learner!",
    "td.nino.superDesc": "Nino B. is a highly rated and experienced tutor.",
    "td.nino.teaches": "Mathematics lessons",
    "td.nino.bio": "Hello! My name is Nino, and I'm a passionate mathematics teacher.\n\nWith over 10 years of experience teaching mathematics, I specialize in making complex concepts accessible and engaging. From algebra to calculus, I tailor each lesson to your learning style and goals.\n\nI have helped hundreds of students improve their grades, pass university entrance exams, and build genuine confidence in math. Whether you're a complete beginner or preparing for advanced exams, I'm here to guide you every step of the way.\n\nTogether, we will explore the beauty of mathematics. I am dedicated to your growth and success, ensuring that each lesson is engaging and tailored to your needs. Let's embark on this learning journey together!",
    "td.giorgi.headline": "PhD in Physics — making physics intuitive, not intimidating. Consistent grade improvements guaranteed!",
    "td.giorgi.superDesc": "Giorgi K. is a highly rated and experienced tutor.",
    "td.giorgi.teaches": "Physics lessons",
    "td.giorgi.bio": "PhD in Physics. I believe physics should be intuitive, not intimidating. My students consistently improve their grades and develop a genuine curiosity for science.\n\nI use real-world examples and visual demonstrations to make abstract concepts concrete. Every lesson is tailored to your current level and goals.",
    "td.ana.headline": "IELTS & TOEFL specialist with Cambridge CELTA certification. Achieve your target scores with structured preparation and real exam practice!",
    "td.ana.superDesc": "Ana M. is a highly rated and experienced tutor.",
    "td.ana.teaches": "English lessons",
    "td.ana.bio": "IELTS & TOEFL specialist with a Cambridge CELTA certification. I help students achieve their target scores with structured preparation and real exam practice.\n\nWith 12 years of experience, I've guided over 500 students to their language goals. My lessons are dynamic, practical, and always tailored to your needs.",
    "td.luka.headline": "Full-stack developer from top tech companies. Learn Python, JavaScript, React, and data science with project-based lessons!",
    "td.luka.teaches": "Programming lessons",
    "td.luka.bio": "Full-stack developer with experience at top tech companies. I teach Python, JavaScript, React, and data science. Project-based learning approach.\n\nI believe the best way to learn programming is by building real projects. Every lesson includes hands-on coding exercises.",
    // Tutor data - reviews
    "td.rev.sandro": "Sandro M.",
    "td.rev.natia": "Natia K.",
    "td.rev.alex": "Alex T.",
    "td.rev.anonymous": "Anonymous",
    "td.rev.mariam": "Mariam D.",
    "td.rev.tamta": "Tamta G.",
    "td.rev.sandro.text": "Another great lesson! Thank you so much! The explanations are always clear and the pace is perfect.",
    "td.rev.natia.text": "An amazing teacher. Wonderful personality — always cheerful, supportive, and encouraging. Very kind and patient, and always makes sure to meet all my learning needs. I'm learning faster and getting better every day.",
    "td.rev.alex.text": "Extremely professional instructor. Lectures are very clear, the teaching materials are highly engaging, and the methods are flexibly adjusted according to students' individual situations. I have gained a great deal and strongly recommend this teacher.",
    "td.rev.anonymous.text": "Top Tutor. I highly recommend to everyone who wants to learn in a very structured way.",
    "td.rev.mariam.text": "Excellent teacher!",
    "td.rev.tamta.text": "Very good tutor. Explains everything clearly and corrects me when I'm wrong. Lessons are engaging and tailored to my needs. I've seen great progress thanks to the guidance ☺️",
    // Tutor search bios
    "td.search.nino.bio": "10+ years teaching mathematics. Specializing in calculus and algebra.",
    "td.search.giorgi.bio": "PhD in Physics. Making complex concepts simple and fun.",
    "td.search.ana.bio": "IELTS & TOEFL specialist. Native-level English teacher.",
    "td.search.luka.bio": "Full-stack developer teaching Python, JavaScript, and more.",
    "td.search.mariam.bio": "University professor with a passion for organic chemistry.",
    "td.search.davit.bio": "Language specialist for international learners.",
    "td.search.elena.bio": "Certified Russian teacher with 8 years of experience.",
    "td.search.tamta.bio": "Conservatory graduate. Piano and vocal lessons for all levels.",

  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("en");

  const handleSetLang = (_newLang: Language) => {
    setLang("en");
    localStorage.setItem("learneazy-lang", "en");
  };

  const t = (key: string): string => {
    return translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
