import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ka" | "ru";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.findTutors": "Find Tutors",
    "nav.forBusiness": "For Business",
    "nav.becomeTutor": "Become a Tutor",
    "nav.provenProgress": "Proven Progress",
    "nav.faq": "FAQ",
    "nav.login": "Log in",
    "nav.signup": "Sign up",
    "nav.profile": "Profile",

    // Profile Settings
    "profile.settings.title": "Profile Settings",
    "profile.settings.desc": "Update your display name and profile picture.",
    "profile.settings.clickToUpload": "Click to upload a photo",
    "profile.settings.avatarUpdated": "Avatar updated!",
    "profile.settings.saved": "Profile saved!",
    "profile.settings.saving": "Saving...",
    "profile.settings.save": "Save Changes",
    "profile.settings.error": "Error",
    "profile.settings.imageOnly": "Please select an image file.",
    "profile.settings.fileTooLarge": "File must be under 2 MB.",

    // Hero
    "hero.badge": "Trusted by 50,000+ students",
    "hero.title1": "Find the perfect",
    "hero.title2": "tutor for you",
    "hero.subtitle": "Connect with expert tutors in any subject. Personalized 1-on-1 lessons that fit your schedule and learning goals.",
    "hero.searchPlaceholder": "What do you want to learn?",
    "hero.search": "Search",
    "hero.nextLesson": "Next Lesson",
    "hero.nextLessonDesc": "Mathematics with Nino B.",
    "hero.joinNow": "Join Now",

    // Homepage
    "home.heroTitle": "Learn faster with your best language tutor.",
    "home.heroCta": "Find your tutor",
    "stats.tutors": "Experienced tutors",
    "stats.reviews": "5-star tutor reviews",
    "stats.subjects": "Subjects taught",
    "stats.nationalities": "Tutor nationalities",
    "stats.appRating": "on the App Store",
    "stats.lessons": "Lessons Completed",
    "stats.rating": "Average Rating",
    "home.teachers": "teachers",
    "home.subj.english": "English tutors",
    "home.subj.georgian": "Georgian tutors",
    "home.subj.russian": "Russian tutors",
    "home.subj.math": "Math tutors",
    "home.subj.programming": "Programming tutors",
    "home.subj.physics": "Physics tutors",
    "home.subj.music": "Music tutors",
    "home.subj.exam": "Exam tutors",
    "home.subj.business": "Business tutors",
    "home.progressBadge": "Verified Results Platform",
    "home.progressTitle": "Real progress, measured and proven",
    "home.progressDesc": "LearnEazy tracks your learning journey so you can see exactly how far you've come. Our data-driven approach ensures every lesson moves you forward.",
    "home.progressFeat1Title": "Trackable Milestones",
    "home.progressFeat1Desc": "Set goals, track completion, and celebrate breakthroughs with detailed progress dashboards.",
    "home.progressFeat2Title": "Personalized Learning Paths",
    "home.progressFeat2Desc": "AI-powered recommendations adapt your curriculum based on strengths and areas to improve.",
    "home.progressFeat3Title": "Outcome Guarantee",
    "home.progressFeat3Desc": "If you don't see measurable improvement, we'll match you with a new tutor — free of charge.",
    "home.howTitle": "How LearnEazy works:",
    "home.how1.title": "Find your tutor.",
    "home.how1.desc": "We'll connect you with a tutor who motivates, challenges, and supports you — from first lesson to mastery.",
    "home.how2.title": "Start learning.",
    "home.how2.desc": "Your tutor will tailor every lesson to your learning goals, so progress feels personal from the very beginning.",
    "home.how3.title": "Make progress every week.",
    "home.how3.desc": "Choose how many lessons you want to take and build lasting confidence, one conversation at a time.",
    "home.guaranteeTitle": "Lessons you'll love. Guaranteed.",
    "home.guaranteeDesc": "Try another tutor for free if you're not satisfied.",
    "home.becomeTutorTitle": "Become a tutor",
    "home.becomeTutorDesc": "Earn money sharing your expert knowledge with students. Sign up to start tutoring online with LearnEazy.",
    "home.tutorBenefit1": "Find new students",
    "home.tutorBenefit2": "Grow your business",
    "home.tutorBenefit3": "Get paid securely",
    "home.becomeTutorBtn": "Become a tutor",
    "home.howPlatformWorks": "How our platform works",
    "home.corpTitle": "Language training for business",
    "home.corpDesc": "LearnEazy corporate training is designed for teams and businesses offering personalized language learning with online tutors.",
    "home.corpCta": "Book a demo",

    // How it works (legacy)
    "how.title": "How LearnEazy Works",
    "how.subtitle": "Start learning in 3 simple steps",
    "how.step1.title": "Find Your Tutor",
    "how.step1.desc": "Browse expert tutors by subject, price, and availability.",
    "how.step2.title": "Book a Lesson",
    "how.step2.desc": "Choose a time that works for you and book with one click.",
    "how.step3.title": "Start Learning",
    "how.step3.desc": "Join your AI-powered classroom and achieve your goals.",

    // CTA
    "cta.title": "Ready to start learning?",
    "cta.subtitle": "Join thousands of students already learning with LearnEazy. Your first trial lesson is free.",
    "cta.button": "Find a Tutor",

    // Footer
    "footer.desc": "Connect with expert tutors worldwide. Learn any subject, any language, at your own pace.",
    "footer.platform": "Platform",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.findTutors": "Find Tutors",
    "footer.aiPractice": "AI Practice",
    "footer.becomeTutor": "Become a Tutor",
    "footer.faq": "FAQ",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy Policy",
    "footer.about": "About",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.rights": "All rights reserved.",

    // Search
    "search.placeholder": "Search tutors by name or subject...",
    "search.filters": "Filters",
    "search.subject": "Subject",
    "search.pricePerHour": "Price per hour (₾)",
    "search.rating": "Rating",
    "search.availability": "Availability",
    "search.nativeSpeaker": "Native Speaker",
    "search.found": "found",
    "search.tutor": "tutor",
    "search.tutors": "tutors",
    "search.noResults": "No tutors found",
    "search.adjustFilters": "Try adjusting your filters",
    "search.native": "Native",

    // Tutor profile
    "profile.tutor": "Tutor",
    "profile.experience": "Experience",
    "profile.students": "Students",
    "profile.lessons": "Lessons",
    "profile.about": "About me",
    "profile.reviews": "Student Reviews",
    "profile.availableTimes": "Available Times",
    "profile.bookTrial": "Book Trial Lesson",
    "profile.sendMessage": "Send Message",
    "profile.freeTrial": "Free trial lesson",
    "profile.cancelAnytime": "Cancel anytime",
    "profile.aiClassroom": "AI-powered classroom",

    // Booking
    "booking.back": "Back to tutor profile",
    "booking.title": "Book Your Lesson",
    "booking.lessonDetails": "Lesson Details",
    "booking.date": "Date",
    "booking.time": "Time",
    "booking.total": "Total",
    "booking.trialTitle": "Book a trial lesson",
    "booking.trialDesc": "To discuss your level and learning plan",
    "booking.duration25": "25 mins",
    "booking.duration50": "50 mins",
    "booking.timezone": "In your time zone, Asia/Tbilisi (GMT +4:00)",
    "booking.morning": "Morning",
    "booking.afternoon": "Afternoon",
    "booking.evening": "Evening",
    "booking.continue": "Continue",
    "booking.selectTime": "Please select a time slot",
    "booking.yourTutor": "Your tutor",
    "booking.students": "students",
    "booking.lessons": "lessons",
    "booking.yearsTeaching": "years teaching",
    "booking.trialDetails": "Trial lesson details",
    "booking.timeBasedOnLocation": "Time is based on your location",
    "booking.cancelReschedule": "Cancel or reschedule for free until 11:00 on",
    "booking.checkoutInfo": "Checkout info",
    "booking.minLesson": "-min lesson",
    "booking.sslSecure": "Your information is secure and protected.",
    "booking.failed": "Booking failed",
    "booking.studentName": "Your Name",
    "booking.studentNamePlaceholder": "Enter your full name",
    "booking.studentEmail": "Your Email",
    "booking.studentEmailPlaceholder": "Enter your email address",
    "booking.studentPhone": "Phone Number",
    "booking.studentPhonePlaceholder": "Enter your phone number",
    "booking.notes": "Additional Notes",
    "booking.notesPlaceholder": "Any specific topics or goals for the lesson...",
    "booking.submitRequest": "Submit Booking Request",
    "booking.submitting": "Submitting...",
    "booking.thankYou": "Thank you for booking! We will review your request and send payment details to your email within 24 hours. Once payment is confirmed, your session will be scheduled.",
    "booking.thankYouTitle": "Booking Request Sent!",
    "booking.backHome": "Back to Home",
    "booking.viewTutors": "Find More Tutors",

    // Dashboard
    "dash.welcome": "Welcome back, Student!",
    "dash.overview": "Here's your learning overview",
    "dash.totalLessons": "Total Lessons",
    "dash.hoursLearned": "Hours Learned",
    "dash.thisWeek": "This Week",
    "dash.unread": "Unread",
    "dash.upcoming": "Upcoming Lessons",
    "dash.completed": "Completed Lessons",
    "dash.join": "Join",
    "dash.scheduled": "Scheduled",
    "dash.aiInsights": "AI Insights",
    "dash.recentActivity": "Recent Activity",
    "dash.findMore": "Find More Tutors",
    "dash.aiPractice": "AI Practice",

    // AI Practice
    "ai.title": "AI Practice",
    "ai.subtitle": "Daily exercises and scenario practice powered by AI",
    "ai.daily": "Daily Exercises",
    "ai.completed": "completed",
    "ai.startExercise": "Start Exercise with AI",
    "ai.scenario": "Scenario Practice",

    // Classroom
    "class.liveSession": "Live Session",
    "class.video": "Video",
    "class.materials": "Materials",
    "class.chat": "Chat",
    "class.notes": "Notes",
    "class.lessonNotes": "Lesson Notes",
    "class.typePlaceholder": "Type your message...",
    "class.notesPlaceholder": "Take notes here...",

    // Messages
    "msg.search": "Search messages...",
    "msg.typePlaceholder": "Type a message...",

    // For Business
    "biz.title": "LearnEazy for Business",
    "biz.subtitle": "Upskill your team with personalized tutoring and AI-powered learning tools.",
    "biz.cta": "Request a Demo",
    "biz.ctaSub": "Free consultation · No commitment",
    "biz.whyTitle": "Why Companies Choose LearnEazy",
    "biz.feat1.title": "Tailored Training Programs",
    "biz.feat1.desc": "Custom curricula designed around your team's skill gaps and business objectives. From language training to technical upskilling.",
    "biz.feat2.title": "Progress Tracking & Analytics",
    "biz.feat2.desc": "Real-time dashboards showing team progress, engagement metrics, and ROI on your training investment.",
    "biz.feat3.title": "Flexible Scheduling",
    "biz.feat3.desc": "Lessons that fit around your team's work schedule. Morning, evening, and weekend availability.",
    "biz.feat4.title": "AI-Powered Practice",
    "biz.feat4.desc": "Between tutor sessions, your team continues learning with AI exercises tailored to their level and goals.",
    "biz.feat5.title": "Dedicated Account Manager",
    "biz.feat5.desc": "A single point of contact to manage onboarding, scheduling, and reporting for your entire team.",
    "biz.feat6.title": "Volume Discounts",
    "biz.feat6.desc": "Competitive pricing for teams of all sizes. The more seats, the better the rate.",
    "biz.statsTitle": "Trusted by Leading Companies",
    "biz.stat1": "Corporate Clients",
    "biz.stat2": "Employees Trained",
    "biz.stat3": "Average Satisfaction",
    "biz.stat4": "Languages Taught",
    "biz.useCases": "Popular Use Cases",
    "biz.use1.title": "Language Training",
    "biz.use1.desc": "English, Georgian, Russian and more — prepare your team for international business.",
    "biz.use2.title": "Tech Upskilling",
    "biz.use2.desc": "Python, JavaScript, data science — keep your engineering team ahead of the curve.",
    "biz.use3.title": "Onboarding Programs",
    "biz.use3.desc": "Accelerate new hire productivity with structured learning paths and mentoring.",
    "biz.contactTitle": "Ready to transform your team's skills?",
    "biz.contactSub": "Get a customized training plan tailored to your organization's needs.",
    "biz.contactBtn": "Get Started",
    "biz.form.company": "Company Name",
    "biz.form.name": "Contact Name",
    "biz.form.email": "Email",
    "biz.form.phone": "Phone",
    "biz.form.teamSize": "Team Size",
    "biz.form.teamSizePlaceholder": "e.g. 10-50 employees",
    "biz.form.message": "Message",
    "biz.form.messagePlaceholder": "Tell us about your training needs...",
    "biz.form.submit": "Send Inquiry",
    "biz.form.success": "Inquiry sent successfully! We'll be in touch soon.",
    "biz.form.error": "Something went wrong. Please try again.",

    // Become a Tutor
    "tutor.title": "Become a Tutor",
    "tutor.subtitle": "Share your expertise, set your own schedule, and earn on your terms.",
    "tutor.cta": "Create a tutor profile now",
    "tutor.ctaSub": "Free to join · Start earning in days",
    "tutor.whyTitle": "Why Teach on LearnEazy?",
    "tutor.feat1.title": "Set your own rate",
    "tutor.feat1.desc": "Choose your hourly rate and change it anytime. On average, English tutors charge $15-25 per hour.",
    "tutor.feat2.title": "Teach anytime, anywhere",
    "tutor.feat2.desc": "Decide when and how many hours you want to teach. No minimum time commitment or fixed schedule. Be your own boss!",
    "tutor.feat3.title": "Grow professionally",
    "tutor.feat3.desc": "Once you sign up and complete your application, you can be approved and start teaching in as little as three days.",
    "tutor.feat4.title": "Grow Your Brand",
    "tutor.feat4.desc": "Build your reputation with reviews, ratings, and a professional profile page.",
    "tutor.feat5.title": "Secure Payments",
    "tutor.feat5.desc": "Get paid reliably through TBC PayGe or BOG Pay. Weekly payouts, no hassle.",
    "tutor.feat6.title": "Support & Community",
    "tutor.feat6.desc": "Access training resources, teaching tips, and a community of fellow tutors.",
    "tutor.howTitle": "How It Works",
    "tutor.step1.title": "Sign up",
    "tutor.step1.desc": "to create your tutor profile",
    "tutor.step2.title": "Get approved",
    "tutor.step2.desc": "by our team in 5 business days",
    "tutor.step3.title": "Start earning",
    "tutor.step3.desc": "by teaching students all over the world!",
    "tutor.statsTitle": "Join Our Growing Community",
    "tutor.stat1": "Active Tutors",
    "tutor.stat2": "Avg. Monthly Earnings",
    "tutor.stat3": "Tutor Satisfaction",
    "tutor.stat4": "Subjects Available",
    "tutor.reqTitle": "What We Look For",
    "tutor.req1": "Expertise in your subject area",
    "tutor.req2": "Strong communication skills",
    "tutor.req3": "Reliable internet connection",
    "tutor.req4": "Passion for helping students learn",
    "tutor.req5": "Minimum 2 years of teaching or professional experience",
    "tutor.readyTitle": "Get paid to teach online",
    "tutor.readySub": "Connect with thousands of learners around the world and teach from your living room.",
    "tutor.readyBtn": "Create a tutor profile now",
    "tutor.heroHeadline": "Make a living by teaching the largest community of learners worldwide",
    "tutor.teachStudentsTitle": "Teach students from over 180 countries",
    "tutor.teachStudentsDesc": "LearnEazy tutors teach 800,000+ students globally. Join us and you'll have everything you need to teach successfully.",
    "tutor.pf1": "Steady stream of new students",
    "tutor.pf2": "Smart calendar",
    "tutor.pf3": "Interactive classroom",
    "tutor.pf4": "Convenient payment methods",
    "tutor.pf5": "Professional development webinars",
    "tutor.pf6": "Supportive tutor community",
    "tutor.testimonialQuote": "LearnEazy allowed me to make a living without leaving home!",
    "tutor.testimonialAuthor": "Krista A. · English tutor",
    "tutor.faqTitle": "Frequently asked questions",
    "tutor.faq1.q": "What kind of tutors does LearnEazy look for?",
    "tutor.faq1.a": "No specific certification or teaching experience is required! We welcome tutors who:\n\n• Enjoy sharing knowledge and making a difference in students' lives\n• Have outstanding communication skills\n• Are willing to provide a personalized learning experience to international students",
    "tutor.faq2.q": "What subject can I teach?",
    "tutor.faq2.a": "We have over 100 subjects on LearnEazy, including languages, school and university subjects, hobbies and art.",
    "tutor.faq3.q": "How do I become an online tutor at LearnEazy?",
    "tutor.faq3.a": "1. Provide some basic information about yourself\n2. Upload your headshot photo\n3. Describe your strengths as a tutor\n4. Record a short video introduction (up to 2 mins long)\n5. Choose your availability\n\nYou'll see tips and examples at each step of the registration process to help you create a great tutor profile. When you complete registration, our Tutor Success team will review your profile within 5 business days. Once your profile is approved, students from around the world will see it on LearnEazy and will be able to book lessons with you.",
    "tutor.faq4.q": "How can I get my profile approved quickly?",
    "tutor.faq4.a": "Sometimes, we don't approve tutor profiles at the first attempt because the profile photo, video or description doesn't meet our requirements. Make sure you use a real photo of yourself, take the time to record a short video and describe your strengths as a tutor in the description. A surefire way to get approved is to follow the tips given at each step of the registration process.\n\nAlso, be sure to avoid mentioning any contact details, lesson prices or misleading information in your profile description and video.",
    "tutor.faq5.q": "Why should I teach on LearnEazy?",
    "tutor.faq5.a": "Because it's easy and flexible! If you teach with LearnEazy, you:\n\n• Earn by sharing what you know\n• Get a steady stream of new students looking to learn online\n• Manage your lessons and connect with students easily\n• Teach whenever and wherever you want\n• Use safe payment methods\n• Get support from our friendly team through professional development webinars, live chat and email\n• Join a community of expert tutors who are always there for you\n\n...and more to come! We're constantly improving the platform and teaching tools for our tutors based on their needs.",
    "tutor.faq6.q": "What computer equipment do I need to teach on LearnEazy?",
    "tutor.faq6.a": "You will need a laptop or a desktop computer, a stable internet connection, a webcam, and a microphone for conducting lessons in the LearnEazy virtual classroom.",
    "tutor.faq7.q": "Is it free to create a tutor profile on LearnEazy?",
    "tutor.faq7.a": "Yes. It is free to create a tutor profile, get exposure to students, and use LearnEazy's tools and materials. We only charge a commission for the lessons that you have taught.",
    "tutor.faq8.q": "How much can I earn on LearnEazy?",
    "tutor.faq8.a": "Most popular tutors on LearnEazy earn up to $550 a week. Your earnings depend on the hourly rate you set, the number of lessons you teach and how many students continue learning with you after the trial lesson. A tip for newly registered tutors: start with a lower hourly rate to get first students faster. You can change your rate anytime.",
    // Tutor Application Portal
    "tutor.apply.step": "Step",
    "tutor.apply.step1Title": "Personal Information",
    "tutor.apply.step1Desc": "Tell us about yourself so we can get to know you.",
    "tutor.apply.step2Title": "Qualifications & Experience",
    "tutor.apply.step2Desc": "Share your teaching background and credentials.",
    "tutor.apply.step3Title": "Subjects & Rates",
    "tutor.apply.step3Desc": "Choose what you want to teach and set your price.",
    "tutor.apply.step4Title": "Availability & Final Details",
    "tutor.apply.step4Desc": "Let us know when you can teach and confirm your application.",
    "tutor.apply.firstName": "First Name",
    "tutor.apply.lastName": "Last Name",
    "tutor.apply.email": "Email",
    "tutor.apply.phone": "Phone",
    "tutor.apply.country": "Country",
    "tutor.apply.experience": "Teaching Experience",
    "tutor.apply.selectExp": "Select experience level",
    "tutor.apply.education": "Education",
    "tutor.apply.educationPlaceholder": "e.g. Master's in Education, King's College London",
    "tutor.apply.certifications": "Certifications",
    "tutor.apply.certPlaceholder": "e.g. TESOL, IELTS Certified",
    "tutor.apply.bio": "About You",
    "tutor.apply.bioPlaceholder": "Describe yourself, your teaching style, and what makes you a great tutor...",
    "tutor.apply.subjects": "Subjects You Teach",
    "tutor.apply.rate": "Hourly Rate",
    "tutor.apply.nativeLang": "Native Language",
    "tutor.apply.otherLangs": "Other Languages",
    "tutor.apply.availability": "Weekly Availability",
    "tutor.apply.selectAvail": "Select availability",
    "tutor.apply.timezone": "Timezone",
    "tutor.apply.aboutTeaching": "Your Teaching Philosophy",
    "tutor.apply.aboutTeachingPlaceholder": "Describe how you approach teaching and what students can expect...",
    "tutor.apply.terms": "I agree to the Terms of Service and confirm that the information provided is accurate.",
    "tutor.apply.back": "Back",
    "tutor.apply.next": "Continue",
    "tutor.apply.submit": "Submit Application",
    "tutor.apply.submitting": "Submitting...",
    "tutor.apply.error": "Something went wrong. Please try again.",
    "tutor.apply.successTitle": "Application Submitted!",
    "tutor.apply.successDesc": "Thank you for applying! Our team will review your application and get back to you within 48 hours.",
    "tutor.apply.backHome": "Back to Home",

    // Tutor Apply - Video
    "tutor.apply.videoLabel": "Introduction Video",
    "tutor.apply.videoDesc": "Record a 1-minute video about yourself and your teaching style. This is optional but highly encouraged — tutors with intro videos get up to 3x more bookings!",
    "tutor.apply.videoPlaceholder": "Paste a YouTube or Google Drive link to your video",
    "tutor.apply.videoTip": "Tip: Keep it short (under 2 min), speak clearly, and show your personality!",

    // Auth
    "auth.login": "Log in",
    "auth.loginDesc": "Welcome back! Sign in to your account.",
    "auth.signup": "Sign up",
    "auth.signupDesc": "Create your account to get started.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.displayName": "Display Name",
    "auth.displayNamePlaceholder": "Your name",
    "auth.forgotPassword": "Forgot password?",
    "auth.forgotDesc": "Enter your email and we'll send you a reset link.",
    "auth.sendResetLink": "Send reset link",
    "auth.sending": "Sending...",
    "auth.resetSent": "Check your email for the password reset link.",
    "auth.backToLogin": "Back to login",
    "auth.noAccount": "Don't have an account?",
    "auth.signupLink": "Sign up",
    "auth.hasAccount": "Already have an account?",
    "auth.loginLink": "Log in",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.error": "Error",
    "auth.welcomeBack": "Welcome back!",
    "auth.checkEmail": "Check your email",
    "auth.verifyEmail": "We sent you a verification link. Please check your email to confirm your account.",
    "auth.passwordMin": "Password must be at least 6 characters.",
    "auth.newPassword": "Set new password",
    "auth.newPasswordDesc": "Enter your new password below.",
    "auth.updatePassword": "Update password",
    "auth.updating": "Updating...",
    "auth.passwordUpdated": "Password updated successfully!",
    "auth.logout": "Log out",
    "auth.dashboard": "Dashboard",
  },
  ka: {
    // Nav
    "nav.home": "მთავარი",
    "nav.findTutors": "რეპეტიტორები",
    "nav.forBusiness": "ბიზნესისთვის",
    "nav.becomeTutor": "გახდი რეპეტიტორი",
    "nav.provenProgress": "პროგრესი",
    "nav.faq": "FAQ",
    "nav.login": "შესვლა",
    "nav.signup": "რეგისტრაცია",
    "nav.profile": "პროფილი",

    // Profile Settings
    "profile.settings.title": "პროფილის პარამეტრები",
    "profile.settings.desc": "განაახლეთ სახელი და პროფილის ფოტო.",
    "profile.settings.clickToUpload": "დააჭირეთ ფოტოს ასატვირთად",
    "profile.settings.avatarUpdated": "ავატარი განახლდა!",
    "profile.settings.saved": "პროფილი შენახულია!",
    "profile.settings.saving": "ინახება...",
    "profile.settings.save": "ცვლილებების შენახვა",
    "profile.settings.error": "შეცდომა",
    "profile.settings.imageOnly": "გთხოვთ აირჩიოთ სურათის ფაილი.",
    "profile.settings.fileTooLarge": "ფაილი უნდა იყოს 2 მბ-ზე ნაკლები.",

    // Hero
    "hero.badge": "50,000+ სტუდენტის ნდობით",
    "hero.title1": "იპოვეთ იდეალური",
    "hero.title2": "რეპეტიტორი",
    "hero.subtitle": "დაუკავშირდით ექსპერტ რეპეტიტორებს ნებისმიერ საგანში. პერსონალიზებული 1-on-1 გაკვეთილები.",
    "hero.searchPlaceholder": "რა გსურთ ისწავლოთ?",
    "hero.search": "ძიება",
    "hero.nextLesson": "შემდეგი გაკვეთილი",
    "hero.nextLessonDesc": "მათემატიკა ნინო ბ.-თან",
    "hero.joinNow": "შესვლა",

    // Homepage
    "home.heroTitle": "ისწავლე სწრაფად საუკეთესო ენის რეპეტიტორთან.",
    "home.heroCta": "იპოვეთ რეპეტიტორი",
    "home.teachers": "მასწავლებელი",
    "home.subj.english": "ინგლისურის რეპეტიტორები",
    "home.subj.georgian": "ქართულის რეპეტიტორები",
    "home.subj.russian": "რუსულის რეპეტიტორები",
    "home.subj.math": "მათემატიკის რეპეტიტორები",
    "home.subj.programming": "პროგრამირების რეპეტიტორები",
    "home.subj.physics": "ფიზიკის რეპეტიტორები",
    "home.subj.music": "მუსიკის რეპეტიტორები",
    "home.subj.exam": "გამოცდის რეპეტიტორები",
    "home.subj.business": "ბიზნესის რეპეტიტორები",
    "home.progressBadge": "დადასტურებული შედეგების პლატფორმა",
    "home.progressTitle": "რეალური პროგრესი, გაზომილი და დადასტურებული",
    "home.progressDesc": "LearnEazy აკონტროლებს თქვენს სწავლის გზას, რომ ზუსტად ნახოთ რამდენი წინსვლა გაქვთ.",
    "home.progressFeat1Title": "თვალყურის დევნება",
    "home.progressFeat1Desc": "დასახეთ მიზნები, თვალყური ადევნეთ შესრულებას და იზეიმეთ წარმატებები.",
    "home.progressFeat2Title": "პერსონალიზებული სწავლის გეგმა",
    "home.progressFeat2Desc": "AI-ზე დაფუძნებული რეკომენდაციები ადაპტირებს კურიკულუმს თქვენი ძლიერი მხარეების მიხედვით.",
    "home.progressFeat3Title": "შედეგის გარანტია",
    "home.progressFeat3Desc": "თუ გაზომვადი გაუმჯობესება ვერ ნახეთ, ახალ რეპეტიტორთან დაგაკავშირებთ — უფასოდ.",
    "home.howTitle": "როგორ მუშაობს LearnEazy:",
    "home.how1.title": "იპოვეთ რეპეტიტორი.",
    "home.how1.desc": "დაგაკავშირებთ რეპეტიტორთან, რომელიც მოტივაციას მოგცემთ და დაგეხმარებათ.",
    "home.how2.title": "დაიწყეთ სწავლა.",
    "home.how2.desc": "რეპეტიტორი მოარგებს ყოველ გაკვეთილს თქვენს სწავლის მიზნებს.",
    "home.how3.title": "წინსვლა ყოველ კვირას.",
    "home.how3.desc": "აირჩიეთ რამდენი გაკვეთილი გსურთ და ააშენეთ მყარი თავდაჯერებულობა.",
    "home.guaranteeTitle": "გაკვეთილები, რომლებიც მოგეწონებათ. გარანტირებული.",
    "home.guaranteeDesc": "სცადეთ სხვა რეპეტიტორი უფასოდ, თუ კმაყოფილი არ ხართ.",
    "home.becomeTutorTitle": "გახდი რეპეტიტორი",
    "home.becomeTutorDesc": "იშოვეთ თქვენი ექსპერტული ცოდნის გაზიარებით. დარეგისტრირდით LearnEazy-ზე.",
    "home.tutorBenefit1": "იპოვეთ ახალი სტუდენტები",
    "home.tutorBenefit2": "გაზარდეთ ბიზნესი",
    "home.tutorBenefit3": "მიიღეთ გადახდა უსაფრთხოდ",
    "home.becomeTutorBtn": "გახდი რეპეტიტორი",
    "home.howPlatformWorks": "როგორ მუშაობს პლატფორმა",
    "home.corpTitle": "ენის სწავლება ბიზნესისთვის",
    "home.corpDesc": "LearnEazy კორპორატიული ტრენინგი შექმნილია გუნდებისთვის პერსონალიზებული ენის სწავლებით.",
    "home.corpCta": "დაჯავშნეთ დემო",

    // Tutor Apply - Video
    "tutor.apply.videoLabel": "შესავალი ვიდეო",
    "tutor.apply.videoDesc": "ჩაწერეთ 1-წუთიანი ვიდეო თქვენს შესახებ და სწავლების სტილზე. არჩევითია, მაგრამ რეკომენდებულია — ვიდეოიანი რეპეტიტორები 3-ჯერ მეტ ჯავშანს იღებენ!",
    "tutor.apply.videoPlaceholder": "ჩასვით YouTube ან Google Drive ბმული",
    "tutor.apply.videoTip": "რჩევა: გააკეთეთ მოკლე (2 წუთამდე), ილაპარაკეთ ნათლად და აჩვენეთ ინდივიდუალობა!",

    // Stats
    "stats.tutors": "ექსპერტი რეპეტიტორი",
    "stats.reviews": "5-ვარსკვლავიანი შეფასება",
    "stats.nationalities": "რეპეტიტორის ეროვნება",
    "stats.appRating": "App Store-ში",
    "stats.lessons": "გაკვეთილი ჩატარებულია",
    "stats.rating": "საშუალო რეიტინგი",
    "stats.subjects": "საგანი",

    // Featured
    "featured.title": "გამორჩეული რეპეტიტორები",
    "featured.subtitle": "საუკეთესო პედაგოგები მზად არიან დაგეხმარონ",
    "featured.viewAll": "ყველას ნახვა",
    "featured.bookTrial": "საცდელი",

    // How it works
    "how.title": "როგორ მუშაობს LearnEazy",
    "how.subtitle": "დაიწყეთ სწავლა 3 მარტივი ნაბიჯით",
    "how.step1.title": "იპოვეთ რეპეტიტორი",
    "how.step1.desc": "მოძებნეთ რეპეტიტორები საგნის, ფასის და ხელმისაწვდომობის მიხედვით.",
    "how.step2.title": "დაჯავშნეთ გაკვეთილი",
    "how.step2.desc": "აირჩიეთ მოსახერხებელი დრო და დაჯავშნეთ ერთი დაწკაპუნებით.",
    "how.step3.title": "დაიწყეთ სწავლა",
    "how.step3.desc": "შეუერთდით AI საკლასო ოთახს და მიაღწიეთ თქვენს მიზნებს.",

    // CTA
    "cta.title": "მზად ხართ სწავლის დასაწყებად?",
    "cta.subtitle": "შეუერთდით ათასობით სტუდენტს, რომლებიც უკვე სწავლობენ LearnEazy-ით. პირველი საცდელი გაკვეთილი უფასოა.",
    "cta.button": "რეპეტიტორის პოვნა",

    // Footer
    "footer.desc": "დაუკავშირდით ექსპერტ რეპეტიტორებს მთელ მსოფლიოში. ისწავლეთ ნებისმიერი საგანი, თქვენი ტემპით.",
    "footer.platform": "პლატფორმა",
    "footer.support": "მხარდაჭერა",
    "footer.company": "კომპანია",
    "footer.findTutors": "რეპეტიტორები",
    "footer.aiPractice": "AI პრაქტიკა",
    "footer.becomeTutor": "გახდი რეპეტიტორი",
    "footer.faq": "FAQ",
    "footer.contact": "კონტაქტი",
    "footer.privacy": "კონფიდენციალურობა",
    "footer.about": "ჩვენ შესახებ",
    "footer.blog": "ბლოგი",
    "footer.careers": "კარიერა",
    "footer.rights": "ყველა უფლება დაცულია.",

    // Search
    "search.placeholder": "მოძებნეთ რეპეტიტორი სახელით ან საგნით...",
    "search.filters": "ფილტრები",
    "search.subject": "საგანი",
    "search.pricePerHour": "ფასი საათში (₾)",
    "search.rating": "რეიტინგი",
    "search.availability": "ხელმისაწვდომობა",
    "search.nativeSpeaker": "მშობლიურენოვანი",
    "search.found": "ნაპოვნია",
    "search.tutor": "რეპეტიტორი",
    "search.tutors": "რეპეტიტორი",
    "search.noResults": "რეპეტიტორები ვერ მოიძებნა",
    "search.adjustFilters": "სცადეთ ფილტრების შეცვლა",
    "search.native": "მშობლიური",

    // Tutor profile
    "profile.tutor": "რეპეტიტორი",
    "profile.experience": "გამოცდილება",
    "profile.students": "სტუდენტები",
    "profile.lessons": "გაკვეთილები",
    "profile.about": "ჩემ შესახებ",
    "profile.reviews": "სტუდენტების შეფასებები",
    "profile.availableTimes": "ხელმისაწვდომი დრო",
    "profile.bookTrial": "საცდელი გაკვეთილის დაჯავშნა",
    "profile.sendMessage": "შეტყობინების გაგზავნა",
    "profile.freeTrial": "უფასო საცდელი გაკვეთილი",
    "profile.cancelAnytime": "გაუქმება ნებისმიერ დროს",
    "profile.aiClassroom": "AI საკლასო ოთახი",

    // Booking
    "booking.back": "პროფილზე დაბრუნება",
    "booking.title": "დაჯავშნეთ გაკვეთილი",
    "booking.lessonDetails": "გაკვეთილის დეტალები",
    "booking.date": "თარიღი",
    "booking.time": "დრო",
    "booking.total": "სულ",
    "booking.trialTitle": "საცდელი გაკვეთილის დაჯავშნა",
    "booking.trialDesc": "თქვენი დონისა და სასწავლო გეგმის განსახილველად",
    "booking.duration25": "25 წთ",
    "booking.duration50": "50 წთ",
    "booking.timezone": "თქვენს დროის ზონაში, Asia/Tbilisi (GMT +4:00)",
    "booking.morning": "დილა",
    "booking.afternoon": "შუადღე",
    "booking.evening": "საღამო",
    "booking.continue": "გაგრძელება",
    "booking.selectTime": "გთხოვთ აირჩიოთ დრო",
    "booking.yourTutor": "თქვენი რეპეტიტორი",
    "booking.students": "სტუდენტი",
    "booking.lessons": "გაკვეთილი",
    "booking.yearsTeaching": "წელი სწავლება",
    "booking.trialDetails": "საცდელი გაკვეთილის დეტალები",
    "booking.timeBasedOnLocation": "დრო დაფუძნებულია თქვენს ლოკაციაზე",
    "booking.cancelReschedule": "უფასოდ გაუქმება ან გადატანა 11:00-მდე",
    "booking.checkoutInfo": "გადახდის ინფორმაცია",
    "booking.minLesson": "-წთ გაკვეთილი",
    "booking.choosePayment": "აირჩიეთ გადახდის მეთოდი",
    "booking.card": "ბარათი",
    "booking.cardNumber": "ბარათის ნომერი",
    "booking.expiry": "თთ/წწ",
    "booking.cvc": "CVC",
    "booking.bookAndPay": "გაკვეთილის დაჯავშნა და გადახდა",
    "booking.booking": "ჯავშნდება...",
    "booking.agreePolicy": "ღილაკზე დაჭერით ეთანხმებით LearnEazy-ის თანხის დაბრუნების პოლიტიკას.",
    "booking.sslSecure": "LearnEazy-ზე გადახდა უსაფრთხოა. ყველა ტრანზაქცია დაცულია SSL დაშიფვრით.",
    "booking.failed": "დაჯავშნა ვერ მოხერხდა",
    "booking.studentName": "თქვენი სახელი",
    "booking.studentNamePlaceholder": "შეიყვანეთ სრული სახელი",
    "booking.studentEmail": "თქვენი ელ-ფოსტა",
    "booking.studentEmailPlaceholder": "შეიყვანეთ ელ-ფოსტის მისამართი",
    "booking.studentPhone": "ტელეფონის ნომერი",
    "booking.studentPhonePlaceholder": "შეიყვანეთ ტელეფონის ნომერი",
    "booking.notes": "დამატებითი ჩანაწერები",
    "booking.notesPlaceholder": "კონკრეტული თემები ან მიზნები გაკვეთილისთვის...",
    "booking.submitRequest": "დაჯავშნის მოთხოვნის გაგზავნა",
    "booking.submitting": "იგზავნება...",
    "booking.thankYou": "გმადლობთ დაჯავშნისთვის! ჩვენ განვიხილავთ თქვენს მოთხოვნას და გამოგიგზავნით გადახდის დეტალებს თქვენს ელფოსტაზე 24 საათის განმავლობაში. გადახდის დადასტურების შემდეგ თქვენი სესია დაიგეგმება.",
    "booking.thankYouTitle": "დაჯავშნის მოთხოვნა გაგზავნილია!",
    "booking.backHome": "მთავარ გვერდზე",
    "booking.viewTutors": "მეტი რეპეტიტორი",

    // Dashboard
    "dash.welcome": "მოგესალმებით, სტუდენტო!",
    "dash.overview": "თქვენი სწავლის მიმოხილვა",
    "dash.totalLessons": "სულ გაკვეთილები",
    "dash.hoursLearned": "სწავლის საათები",
    "dash.thisWeek": "ამ კვირაში",
    "dash.unread": "წაუკითხავი",
    "dash.upcoming": "მომავალი გაკვეთილები",
    "dash.completed": "დასრულებული გაკვეთილები",
    "dash.join": "შესვლა",
    "dash.scheduled": "დაგეგმილი",
    "dash.aiInsights": "AI ანალიზი",
    "dash.recentActivity": "ბოლო აქტივობა",
    "dash.findMore": "მეტი რეპეტიტორი",
    "dash.aiPractice": "AI პრაქტიკა",

    // AI Practice
    "ai.title": "AI პრაქტიკა",
    "ai.subtitle": "ყოველდღიური სავარჯიშოები და სცენარული პრაქტიკა AI-ით",
    "ai.daily": "ყოველდღიური სავარჯიშოები",
    "ai.completed": "დასრულებულია",
    "ai.startExercise": "სავარჯიშოს დაწყება AI-ით",
    "ai.scenario": "სცენარული პრაქტიკა",

    // Classroom
    "class.liveSession": "პირდაპირი სესია",
    "class.video": "ვიდეო",
    "class.materials": "მასალები",
    "class.chat": "ჩატი",
    "class.notes": "ჩანაწერები",
    "class.lessonNotes": "გაკვეთილის ჩანაწერები",
    "class.typePlaceholder": "დაწერეთ შეტყობინება...",
    "class.notesPlaceholder": "ჩაინიშნეთ აქ...",

    // Messages
    "msg.search": "შეტყობინებების ძიება...",
    "msg.typePlaceholder": "დაწერეთ შეტყობინება...",

    // For Business
    "biz.title": "LearnEazy ბიზნესისთვის",
    "biz.subtitle": "გაზარდეთ თქვენი გუნდის კვალიფიკაცია პერსონალიზებული რეპეტიტორობით და AI სასწავლო ხელსაწყოებით.",
    "biz.cta": "მოითხოვეთ დემო",
    "biz.ctaSub": "უფასო კონსულტაცია · ვალდებულების გარეშე",
    "biz.whyTitle": "რატომ ირჩევენ კომპანიები LearnEazy-ს",
    "biz.feat1.title": "მორგებული სასწავლო პროგრამები",
    "biz.feat1.desc": "თქვენი გუნდის საჭიროებებზე მორგებული კურიკულუმი. ენების სწავლებიდან ტექნიკურ უნარებამდე.",
    "biz.feat2.title": "პროგრესის თვალყურის დევნება",
    "biz.feat2.desc": "რეალურ დროში დაფები გუნდის პროგრესით და ჩართულობის მეტრიკებით.",
    "biz.feat3.title": "მოქნილი განრიგი",
    "biz.feat3.desc": "გაკვეთილები, რომლებიც თქვენი გუნდის სამუშაო განრიგს ეთანადება.",
    "biz.feat4.title": "AI პრაქტიკა",
    "biz.feat4.desc": "რეპეტიტორის სესიებს შორის თქვენი გუნდი აგრძელებს სწავლას AI სავარჯიშოებით.",
    "biz.feat5.title": "პერსონალური მენეჯერი",
    "biz.feat5.desc": "ერთი საკონტაქტო პირი ონბორდინგის, განრიგისა და ანგარიშგებისთვის.",
    "biz.feat6.title": "მოცულობის ფასდაკლებები",
    "biz.feat6.desc": "კონკურენტუნარიანი ფასები ყველა ზომის გუნდისთვის.",
    "biz.statsTitle": "წამყვანი კომპანიების ნდობით",
    "biz.stat1": "კორპორატიული კლიენტი",
    "biz.stat2": "გადამზადებული თანამშრომელი",
    "biz.stat3": "საშუალო კმაყოფილება",
    "biz.stat4": "სასწავლო ენა",
    "biz.useCases": "პოპულარული გამოყენება",
    "biz.use1.title": "ენის სწავლება",
    "biz.use1.desc": "ინგლისური, ქართული, რუსული — მოამზადეთ გუნდი საერთაშორისო ბიზნესისთვის.",
    "biz.use2.title": "ტექნიკური კვალიფიკაცია",
    "biz.use2.desc": "Python, JavaScript, მონაცემთა მეცნიერება — შეინარჩუნეთ ინჟინრების წამყვანი პოზიცია.",
    "biz.use3.title": "ონბორდინგის პროგრამები",
    "biz.use3.desc": "დააჩქარეთ ახალი თანამშრომლების პროდუქტიულობა სტრუქტურირებული სასწავლო გეგმებით.",
    "biz.contactTitle": "მზად ხართ გუნდის უნარების ტრანსფორმაციისთვის?",
    "biz.contactSub": "მიიღეთ მორგებული სასწავლო გეგმა თქვენი ორგანიზაციისთვის.",
    "biz.contactBtn": "დაწყება",
    "biz.form.company": "კომპანიის სახელი",
    "biz.form.name": "საკონტაქტო პირი",
    "biz.form.email": "ელ. ფოსტა",
    "biz.form.phone": "ტელეფონი",
    "biz.form.teamSize": "გუნდის ზომა",
    "biz.form.teamSizePlaceholder": "მაგ. 10-50 თანამშრომელი",
    "biz.form.message": "შეტყობინება",
    "biz.form.messagePlaceholder": "მოგვიყევით თქვენი სასწავლო საჭიროებების შესახებ...",
    "biz.form.submit": "მოთხოვნის გაგზავნა",
    "biz.form.success": "მოთხოვნა წარმატებით გაიგზავნა! მალე დაგიკავშირდებით.",
    "biz.form.error": "რაღაც შეცდომა მოხდა. სცადეთ ხელახლა.",

    // Become a Tutor
    "tutor.title": "გახდი რეპეტიტორი",
    "tutor.subtitle": "გაუზიარეთ გამოცდილება, დააწესეთ საკუთარი განრიგი და იშოვეთ თქვენი პირობებით.",
    "tutor.cta": "გააკეთეთ განაცხადი",
    "tutor.ctaSub": "უფასო გაწევრიანება · დაიწყეთ შემოსავალი 48 საათში",
    "tutor.whyTitle": "რატომ ასწავლოთ LearnEazy-ზე?",
    "tutor.feat1.title": "დააწესეთ საკუთარი ტარიფები",
    "tutor.feat1.desc": "თქვენ წყვეტთ რამდენი მოითხოვოთ. LearnEazy იღებს მცირე საკომისიოს.",
    "tutor.feat2.title": "მოქნილი განრიგი",
    "tutor.feat2.desc": "ასწავლეთ როცა მოგწონთ. დააწესეთ ხელმისაწვდომობა და მიიღეთ ჯავშნები.",
    "tutor.feat3.title": "AI საკლასო ოთახი",
    "tutor.feat3.desc": "ჩაშენებული ვიდეო, დაფა, ჩანაწერები და AI ანალიზი — ყველაფერი ერთ ადგილას.",
    "tutor.feat4.title": "გაზარდეთ თქვენი ბრენდი",
    "tutor.feat4.desc": "ააშენეთ რეპუტაცია შეფასებებით და პროფესიონალური პროფილით.",
    "tutor.feat5.title": "უსაფრთხო გადახდები",
    "tutor.feat5.desc": "მიიღეთ გადახდები TBC PayGe ან BOG Pay-ით. ყოველკვირეული გადარიცხვები.",
    "tutor.feat6.title": "მხარდაჭერა და საზოგადოება",
    "tutor.feat6.desc": "წვდომა სასწავლო რესურსებზე და რეპეტიტორების საზოგადოებაზე.",
    "tutor.howTitle": "როგორ მუშაობს",
    "tutor.step1.title": "განაცხადი ონლაინ",
    "tutor.step1.desc": "შეავსეთ მოკლე განაცხადი კვალიფიკაციითა და სასწავლო გამოცდილებით.",
    "tutor.step2.title": "ვერიფიკაცია",
    "tutor.step2.desc": "ჩვენი გუნდი განიხილავს განაცხადს და ამოწმებს კვალიფიკაციას 48 საათში.",
    "tutor.step3.title": "დაიწყეთ სწავლება",
    "tutor.step3.desc": "შექმენით პროფილი, აირჩიეთ საგნები და ტარიფები, დაიწყეთ სტუდენტების მიღება.",
    "tutor.statsTitle": "შეუერთდით ჩვენს მზარდ საზოგადოებას",
    "tutor.stat1": "აქტიური რეპეტიტორი",
    "tutor.stat2": "საშ. თვიური შემოსავალი",
    "tutor.stat3": "რეპეტიტორის კმაყოფილება",
    "tutor.stat4": "ხელმისაწვდომი საგანი",
    "tutor.reqTitle": "რას ვეძებთ",
    "tutor.req1": "ექსპერტიზა თქვენს საგანში",
    "tutor.req2": "ძლიერი კომუნიკაციის უნარები",
    "tutor.req3": "საიმედო ინტერნეტ კავშირი",
    "tutor.req4": "სტუდენტების დახმარების ვნება",
    "tutor.req5": "მინიმუმ 2 წლიანი სასწავლო ან პროფესიონალური გამოცდილება",
    "tutor.readyTitle": "მზად ხართ სწავლების დასაწყებად?",
    "tutor.readySub": "შეუერთდით ათასობით რეპეტიტორს. გააკეთეთ განაცხადი დღეს — უფასოა.",
    "tutor.readyBtn": "დაიწყეთ განაცხადი",
    "tutor.heroHeadline": "იშოვეთ საცხოვრებელი მსოფლიოს უდიდესი მოსწავლეების საზოგადოების სწავლებით",
    "tutor.teachStudentsTitle": "ასწავლეთ სტუდენტებს 180+ ქვეყნიდან",
    "tutor.teachStudentsDesc": "LearnEazy-ის რეპეტიტორები ასწავლიან 800,000+ სტუდენტს მთელ მსოფლიოში.",
    "tutor.pf1": "სტუდენტების მუდმივი ნაკადი",
    "tutor.pf2": "ჭკვიანი კალენდარი",
    "tutor.pf3": "ინტერაქტიული საკლასო ოთახი",
    "tutor.pf4": "მოსახერხებელი გადახდის მეთოდები",
    "tutor.pf5": "პროფესიული განვითარების ვებინარები",
    "tutor.pf6": "მხარდამჭერი რეპეტიტორების საზოგადოება",
    "tutor.testimonialQuote": "LearnEazy-მა მომცა საშუალება ვიშოვო სახლიდან გაუსვლელად!",
    "tutor.testimonialAuthor": "ნინო ს. · ინგლისურის რეპეტიტორი",
    "tutor.faqTitle": "ხშირად დასმული კითხვები",
    "tutor.faq1.q": "რა ტიპის რეპეტიტორებს ეძებს LearnEazy?",
    "tutor.faq1.a": "კონკრეტული სერთიფიკატი ან სასწავლო გამოცდილება არ არის საჭირო! მივესალმებით რეპეტიტორებს, რომლებსაც სიამოვნებთ ცოდნის გაზიარება.",
    "tutor.faq2.q": "რა საგანი შემიძლია ვასწავლო?",
    "tutor.faq2.a": "LearnEazy-ზე 100-ზე მეტი საგანია, მათ შორის ენები, სასკოლო და საუნივერსიტეტო საგნები.",
    "tutor.faq3.q": "როგორ გავხდე ონლაინ რეპეტიტორი?",
    "tutor.faq3.a": "1. მიუთითეთ ძირითადი ინფორმაცია\n2. ატვირთეთ ფოტო\n3. აღწერეთ თქვენი ძლიერი მხარეები\n4. ჩაწერეთ მოკლე ვიდეო\n5. აირჩიეთ ხელმისაწვდომობა",
    "tutor.faq4.q": "როგორ დავამტკიცო პროფილი სწრაფად?",
    "tutor.faq4.a": "გამოიყენეთ რეალური ფოტო, ჩაწერეთ მოკლე ვიდეო და აღწერეთ თქვენი ძლიერი მხარეები.",
    "tutor.faq5.q": "რატომ უნდა ვასწავლო LearnEazy-ზე?",
    "tutor.faq5.a": "რადგან ეს მარტივი და მოქნილია! იშოვეთ ცოდნის გაზიარებით, მიიღეთ სტუდენტების ნაკადი, ასწავლეთ სადაც და როცა გინდათ.",
    "tutor.faq6.q": "უფასოა თუ არა პროფილის შექმნა?",
    "tutor.faq6.a": "დიახ. პროფილის შექმნა, სტუდენტებზე წვდომა და ინსტრუმენტების გამოყენება უფასოა. ჩვენ ვიღებთ მცირე საკომისიოს მხოლოდ ჩატარებული გაკვეთილებიდან.",
    "tutor.faq7.q": "რამდენი შემიძლია ვიშოვო?",
    "tutor.faq7.a": "პოპულარული რეპეტიტორები კვირაში $550-მდე შოულობენ. შემოსავალი დამოკიდებულია თქვენს ტარიფზე და გაკვეთილების რაოდენობაზე.",
    "tutor.apply.step": "ნაბიჯი",
    "tutor.apply.step1Title": "პირადი ინფორმაცია",
    "tutor.apply.step1Desc": "გვიამბეთ თქვენს შესახებ.",
    "tutor.apply.step2Title": "კვალიფიკაცია და გამოცდილება",
    "tutor.apply.step2Desc": "გაგვიზიარეთ თქვენი სასწავლო გამოცდილება.",
    "tutor.apply.step3Title": "საგნები და ტარიფები",
    "tutor.apply.step3Desc": "აირჩიეთ რა გსურთ ასწავლოთ და დააწესეთ ფასი.",
    "tutor.apply.step4Title": "ხელმისაწვდომობა და საბოლოო დეტალები",
    "tutor.apply.step4Desc": "გვაცნობეთ როდის შეგიძლიათ სწავლება.",
    "tutor.apply.firstName": "სახელი",
    "tutor.apply.lastName": "გვარი",
    "tutor.apply.email": "ელ-ფოსტა",
    "tutor.apply.phone": "ტელეფონი",
    "tutor.apply.country": "ქვეყანა",
    "tutor.apply.experience": "სასწავლო გამოცდილება",
    "tutor.apply.selectExp": "აირჩიეთ გამოცდილების დონე",
    "tutor.apply.education": "განათლება",
    "tutor.apply.educationPlaceholder": "მაგ. განათლების მაგისტრი",
    "tutor.apply.certifications": "სერთიფიკატები",
    "tutor.apply.certPlaceholder": "მაგ. TESOL, IELTS",
    "tutor.apply.bio": "თქვენს შესახებ",
    "tutor.apply.bioPlaceholder": "აღწერეთ თქვენი სწავლების სტილი...",
    "tutor.apply.subjects": "საგნები",
    "tutor.apply.rate": "საათობრივი ტარიფი",
    "tutor.apply.nativeLang": "მშობლიური ენა",
    "tutor.apply.otherLangs": "სხვა ენები",
    "tutor.apply.availability": "ყოველკვირეული ხელმისაწვდომობა",
    "tutor.apply.selectAvail": "აირჩიეთ ხელმისაწვდომობა",
    "tutor.apply.timezone": "დროის ზონა",
    "tutor.apply.aboutTeaching": "სწავლების ფილოსოფია",
    "tutor.apply.aboutTeachingPlaceholder": "აღწერეთ როგორ მიუდგებით სწავლებას...",
    "tutor.apply.terms": "ვეთანხმები მომსახურების პირობებს და ვადასტურებ ინფორმაციის სიზუსტეს.",
    "tutor.apply.back": "უკან",
    "tutor.apply.next": "გაგრძელება",
    "tutor.apply.submit": "განაცხადის გაგზავნა",
    "tutor.apply.submitting": "იგზავნება...",
    "tutor.apply.error": "რაღაც შეცდომა მოხდა. სცადეთ ხელახლა.",
    "tutor.apply.successTitle": "განაცხადი გაგზავნილია!",
    "tutor.apply.successDesc": "გმადლობთ განაცხადისთვის! ჩვენი გუნდი განიხილავს და 48 საათში დაგიკავშირდებათ.",
    "tutor.apply.backHome": "მთავარ გვერდზე",

    // Auth
    "auth.login": "შესვლა",
    "auth.loginDesc": "კეთილი იყოს თქვენი დაბრუნება! შედით თქვენს ანგარიშში.",
    "auth.signup": "რეგისტრაცია",
    "auth.signupDesc": "შექმენით ანგარიში დასაწყებად.",
    "auth.email": "ელ-ფოსტა",
    "auth.password": "პაროლი",
    "auth.displayName": "სახელი",
    "auth.displayNamePlaceholder": "თქვენი სახელი",
    "auth.forgotPassword": "დაგავიწყდათ პაროლი?",
    "auth.forgotDesc": "შეიყვანეთ ელ-ფოსტა და გამოგიგზავნით აღდგენის ბმულს.",
    "auth.sendResetLink": "აღდგენის ბმულის გაგზავნა",
    "auth.sending": "იგზავნება...",
    "auth.resetSent": "შეამოწმეთ ელ-ფოსტა პაროლის აღდგენის ბმულისთვის.",
    "auth.backToLogin": "შესვლაზე დაბრუნება",
    "auth.noAccount": "არ გაქვთ ანგარიში?",
    "auth.signupLink": "რეგისტრაცია",
    "auth.hasAccount": "უკვე გაქვთ ანგარიში?",
    "auth.loginLink": "შესვლა",
    "auth.signingIn": "შესვლა...",
    "auth.creatingAccount": "ანგარიშის შექმნა...",
    "auth.error": "შეცდომა",
    "auth.welcomeBack": "კეთილი იყოს თქვენი დაბრუნება!",
    "auth.checkEmail": "შეამოწმეთ ელ-ფოსტა",
    "auth.verifyEmail": "გამოგიგზავნეთ დადასტურების ბმული. შეამოწმეთ ელ-ფოსტა ანგარიშის დასადასტურებლად.",
    "auth.passwordMin": "პაროლი უნდა იყოს მინიმუმ 6 სიმბოლო.",
    "auth.newPassword": "ახალი პაროლის დაყენება",
    "auth.newPasswordDesc": "შეიყვანეთ ახალი პაროლი ქვემოთ.",
    "auth.updatePassword": "პაროლის განახლება",
    "auth.updating": "განახლება...",
    "auth.passwordUpdated": "პაროლი წარმატებით განახლდა!",
    "auth.logout": "გასვლა",
    "auth.dashboard": "პანელი",
  },
  ru: {
    // Nav
    "nav.home": "Главная",
    "nav.findTutors": "Репетиторы",
    "nav.forBusiness": "Для бизнеса",
    "nav.becomeTutor": "Стать репетитором",
    "nav.provenProgress": "Прогресс",
    "nav.faq": "FAQ",
    "nav.login": "Войти",
    "nav.signup": "Регистрация",
    "nav.profile": "Профиль",

    // Profile Settings
    "profile.settings.title": "Настройки профиля",
    "profile.settings.desc": "Обновите имя и фото профиля.",
    "profile.settings.clickToUpload": "Нажмите, чтобы загрузить фото",
    "profile.settings.avatarUpdated": "Аватар обновлён!",
    "profile.settings.saved": "Профиль сохранён!",
    "profile.settings.saving": "Сохранение...",
    "profile.settings.save": "Сохранить изменения",
    "profile.settings.error": "Ошибка",
    "profile.settings.imageOnly": "Выберите файл изображения.",
    "profile.settings.fileTooLarge": "Файл должен быть менее 2 МБ.",

    // Hero
    "hero.badge": "Доверяют 50 000+ студентов",
    "hero.title1": "Найдите идеального",
    "hero.title2": "репетитора",
    "hero.subtitle": "Свяжитесь с экспертными репетиторами по любому предмету. Персонализированные уроки 1-на-1.",
    "hero.searchPlaceholder": "Что вы хотите изучить?",
    "hero.search": "Поиск",
    "hero.nextLesson": "Следующий урок",
    "hero.nextLessonDesc": "Математика с Нино Б.",
    "hero.joinNow": "Войти",

    // Homepage
    "home.heroTitle": "Учись быстрее с лучшим языковым репетитором.",
    "home.heroCta": "Найдите репетитора",
    "home.teachers": "преподавателей",
    "home.subj.english": "Репетиторы английского",
    "home.subj.georgian": "Репетиторы грузинского",
    "home.subj.russian": "Репетиторы русского",
    "home.subj.math": "Репетиторы математики",
    "home.subj.programming": "Репетиторы программирования",
    "home.subj.physics": "Репетиторы физики",
    "home.subj.music": "Репетиторы музыки",
    "home.subj.exam": "Репетиторы по экзаменам",
    "home.subj.business": "Репетиторы бизнеса",
    "home.progressBadge": "Платформа подтверждённых результатов",
    "home.progressTitle": "Реальный прогресс, измеренный и доказанный",
    "home.progressDesc": "LearnEazy отслеживает ваш путь обучения, чтобы вы видели свой прогресс.",
    "home.progressFeat1Title": "Отслеживание прогресса",
    "home.progressFeat1Desc": "Ставьте цели, отслеживайте выполнение и отмечайте достижения.",
    "home.progressFeat2Title": "Персонализированный план обучения",
    "home.progressFeat2Desc": "AI-рекомендации адаптируют учебный план под ваши сильные стороны.",
    "home.progressFeat3Title": "Гарантия результата",
    "home.progressFeat3Desc": "Если нет измеримого улучшения, мы подберём нового репетитора — бесплатно.",
    "home.howTitle": "Как работает LearnEazy:",
    "home.how1.title": "Найдите репетитора.",
    "home.how1.desc": "Мы свяжем вас с репетитором, который мотивирует и поддержит.",
    "home.how2.title": "Начните учиться.",
    "home.how2.desc": "Репетитор адаптирует каждый урок под ваши цели обучения.",
    "home.how3.title": "Прогресс каждую неделю.",
    "home.how3.desc": "Выберите количество уроков и развивайте уверенность шаг за шагом.",
    "home.guaranteeTitle": "Уроки, которые вам понравятся. Гарантировано.",
    "home.guaranteeDesc": "Попробуйте другого репетитора бесплатно, если не довольны.",
    "home.becomeTutorTitle": "Станьте репетитором",
    "home.becomeTutorDesc": "Зарабатывайте, делясь экспертными знаниями. Зарегистрируйтесь на LearnEazy.",
    "home.tutorBenefit1": "Находите новых студентов",
    "home.tutorBenefit2": "Развивайте бизнес",
    "home.tutorBenefit3": "Получайте оплату безопасно",
    "home.becomeTutorBtn": "Стать репетитором",
    "home.howPlatformWorks": "Как работает платформа",
    "home.corpTitle": "Языковое обучение для бизнеса",
    "home.corpDesc": "Корпоративное обучение LearnEazy создано для команд с персонализированным языковым обучением.",
    "home.corpCta": "Забронировать демо",

    // Tutor Apply - Video
    "tutor.apply.videoLabel": "Вступительное видео",
    "tutor.apply.videoDesc": "Запишите 1-минутное видео о себе и вашем стиле преподавания. Это необязательно, но рекомендуется — репетиторы с видео получают в 3 раза больше бронирований!",
    "tutor.apply.videoPlaceholder": "Вставьте ссылку на YouTube или Google Drive",
    "tutor.apply.videoTip": "Совет: Будьте кратким (до 2 мин), говорите чётко и покажите свою индивидуальность!",

    // Stats
    "stats.tutors": "Экспертных репетиторов",
    "stats.reviews": "5-звёздочных отзывов",
    "stats.nationalities": "Национальностей репетиторов",
    "stats.appRating": "в App Store",
    "stats.lessons": "Проведённых уроков",
    "stats.rating": "Средний рейтинг",
    "stats.subjects": "Предметов",

    // Featured
    "featured.title": "Лучшие репетиторы",
    "featured.subtitle": "Лучшие педагоги готовы помочь вам",
    "featured.viewAll": "Показать все",
    "featured.bookTrial": "Пробный",

    // How it works
    "how.title": "Как работает LearnEazy",
    "how.subtitle": "Начните обучение в 3 простых шага",
    "how.step1.title": "Найдите репетитора",
    "how.step1.desc": "Ищите репетиторов по предмету, цене и доступности.",
    "how.step2.title": "Забронируйте урок",
    "how.step2.desc": "Выберите удобное время и забронируйте в один клик.",
    "how.step3.title": "Начните учиться",
    "how.step3.desc": "Присоединяйтесь к AI-классу и достигайте своих целей.",

    // CTA
    "cta.title": "Готовы начать обучение?",
    "cta.subtitle": "Присоединяйтесь к тысячам студентов, которые уже учатся с LearnEazy. Первый пробный урок бесплатный.",
    "cta.button": "Найти репетитора",

    // Footer
    "footer.desc": "Свяжитесь с экспертными репетиторами по всему миру. Учитесь в своём темпе.",
    "footer.platform": "Платформа",
    "footer.support": "Поддержка",
    "footer.company": "Компания",
    "footer.findTutors": "Репетиторы",
    "footer.aiPractice": "AI Практика",
    "footer.becomeTutor": "Стать репетитором",
    "footer.faq": "FAQ",
    "footer.contact": "Контакт",
    "footer.privacy": "Конфиденциальность",
    "footer.about": "О нас",
    "footer.blog": "Блог",
    "footer.careers": "Карьера",
    "footer.rights": "Все права защищены.",

    // Search
    "search.placeholder": "Поиск репетиторов по имени или предмету...",
    "search.filters": "Фильтры",
    "search.subject": "Предмет",
    "search.pricePerHour": "Цена в час (₾)",
    "search.rating": "Рейтинг",
    "search.availability": "Доступность",
    "search.nativeSpeaker": "Носитель языка",
    "search.found": "найдено",
    "search.tutor": "репетитор",
    "search.tutors": "репетиторов",
    "search.noResults": "Репетиторы не найдены",
    "search.adjustFilters": "Попробуйте изменить фильтры",
    "search.native": "Носитель",

    // Tutor profile
    "profile.tutor": "Репетитор",
    "profile.experience": "Опыт",
    "profile.students": "Студенты",
    "profile.lessons": "Уроки",
    "profile.about": "Обо мне",
    "profile.reviews": "Отзывы студентов",
    "profile.availableTimes": "Доступное время",
    "profile.bookTrial": "Забронировать пробный урок",
    "profile.sendMessage": "Написать сообщение",
    "profile.freeTrial": "Бесплатный пробный урок",
    "profile.cancelAnytime": "Отмена в любое время",
    "profile.aiClassroom": "AI-класс",

    // Booking
    "booking.back": "Назад к профилю",
    "booking.title": "Забронировать урок",
    "booking.lessonDetails": "Детали урока",
    "booking.date": "Дата",
    "booking.time": "Время",
    "booking.paymentMethod": "Способ оплаты",
    "booking.orderSummary": "Итог заказа",
    "booking.lesson60": "Урок (60 мин)",
    "booking.platformFee": "Комиссия платформы",
    "booking.total": "Итого",
    "booking.complete": "Завершить бронирование",
    "booking.secure": "Безопасная оплата · Гарантия возврата",
    "booking.trialTitle": "Забронировать пробный урок",
    "booking.trialDesc": "Для обсуждения вашего уровня и плана обучения",
    "booking.duration25": "25 мин",
    "booking.duration50": "50 мин",
    "booking.timezone": "В вашем часовом поясе, Asia/Tbilisi (GMT +4:00)",
    "booking.morning": "Утро",
    "booking.afternoon": "День",
    "booking.evening": "Вечер",
    "booking.continue": "Продолжить",
    "booking.selectTime": "Пожалуйста, выберите время",
    "booking.yourTutor": "Ваш репетитор",
    "booking.students": "студентов",
    "booking.lessons": "уроков",
    "booking.yearsTeaching": "лет преподавания",
    "booking.trialDetails": "Детали пробного урока",
    "booking.timeBasedOnLocation": "Время основано на вашем местоположении",
    "booking.cancelReschedule": "Бесплатная отмена или перенос до 11:00",
    "booking.checkoutInfo": "Информация об оплате",
    "booking.minLesson": "-мин урок",
    "booking.choosePayment": "Выберите способ оплаты",
    "booking.card": "Карта",
    "booking.cardNumber": "Номер карты",
    "booking.expiry": "ММ/ГГ",
    "booking.cvc": "CVC",
    "booking.bookAndPay": "Забронировать и оплатить",
    "booking.booking": "Бронирование...",
    "booking.agreePolicy": "Нажимая кнопку, вы соглашаетесь с Политикой возврата и оплаты LearnEazy.",
    "booking.sslSecure": "Оплата на LearnEazy безопасна. Все транзакции защищены SSL-шифрованием.",
    "booking.failed": "Бронирование не удалось",
    "booking.studentName": "Ваше имя",
    "booking.studentNamePlaceholder": "Введите полное имя",
    "booking.studentEmail": "Ваш email",
    "booking.studentEmailPlaceholder": "Введите адрес электронной почты",
    "booking.studentPhone": "Номер телефона",
    "booking.studentPhonePlaceholder": "Введите номер телефона",
    "booking.notes": "Дополнительные заметки",
    "booking.notesPlaceholder": "Конкретные темы или цели для урока...",
    "booking.submitRequest": "Отправить запрос на бронирование",
    "booking.submitting": "Отправка...",
    "booking.thankYou": "Спасибо за бронирование! Мы рассмотрим ваш запрос и отправим реквизиты для оплаты на вашу электронную почту в течение 24 часов. После подтверждения оплаты ваш сеанс будет запланирован.",
    "booking.thankYouTitle": "Запрос на бронирование отправлен!",
    "booking.backHome": "На главную",
    "booking.viewTutors": "Найти репетиторов",

    // Dashboard
    "dash.welcome": "С возвращением, Студент!",
    "dash.overview": "Обзор вашего обучения",
    "dash.totalLessons": "Всего уроков",
    "dash.hoursLearned": "Часов обучения",
    "dash.thisWeek": "На этой неделе",
    "dash.unread": "Непрочитанные",
    "dash.upcoming": "Предстоящие уроки",
    "dash.completed": "Завершённые уроки",
    "dash.join": "Войти",
    "dash.scheduled": "Запланирован",
    "dash.aiInsights": "AI Аналитика",
    "dash.recentActivity": "Последняя активность",
    "dash.findMore": "Ещё репетиторы",
    "dash.aiPractice": "AI Практика",

    // AI Practice
    "ai.title": "AI Практика",
    "ai.subtitle": "Ежедневные упражнения и сценарная практика с AI",
    "ai.daily": "Ежедневные упражнения",
    "ai.completed": "завершено",
    "ai.startExercise": "Начать упражнение с AI",
    "ai.scenario": "Сценарная практика",

    // Classroom
    "class.liveSession": "Прямой эфир",
    "class.video": "Видео",
    "class.materials": "Материалы",
    "class.chat": "Чат",
    "class.notes": "Заметки",
    "class.lessonNotes": "Заметки к уроку",
    "class.typePlaceholder": "Введите сообщение...",
    "class.notesPlaceholder": "Записывайте здесь...",

    // Messages
    "msg.search": "Поиск сообщений...",
    "msg.typePlaceholder": "Введите сообщение...",

    // For Business
    "biz.title": "LearnEazy для бизнеса",
    "biz.subtitle": "Повышайте квалификацию команды с персонализированным обучением и AI-инструментами.",
    "biz.cta": "Запросить демо",
    "biz.ctaSub": "Бесплатная консультация · Без обязательств",
    "biz.whyTitle": "Почему компании выбирают LearnEazy",
    "biz.feat1.title": "Индивидуальные программы",
    "biz.feat1.desc": "Учебные планы, разработанные под потребности вашей команды. От языков до технических навыков.",
    "biz.feat2.title": "Отслеживание прогресса",
    "biz.feat2.desc": "Панели мониторинга в реальном времени с прогрессом команды и метриками вовлечённости.",
    "biz.feat3.title": "Гибкое расписание",
    "biz.feat3.desc": "Уроки, которые вписываются в рабочий график вашей команды.",
    "biz.feat4.title": "AI-практика",
    "biz.feat4.desc": "Между сессиями с репетитором команда продолжает учиться с AI-упражнениями.",
    "biz.feat5.title": "Персональный менеджер",
    "biz.feat5.desc": "Единый контакт для управления онбордингом, расписанием и отчётностью.",
    "biz.feat6.title": "Скидки за объём",
    "biz.feat6.desc": "Конкурентные цены для команд любого размера.",
    "biz.statsTitle": "Нам доверяют ведущие компании",
    "biz.stat1": "Корпоративных клиентов",
    "biz.stat2": "Обученных сотрудников",
    "biz.stat3": "Средняя удовлетворённость",
    "biz.stat4": "Языков обучения",
    "biz.useCases": "Популярные направления",
    "biz.use1.title": "Языковое обучение",
    "biz.use1.desc": "Английский, грузинский, русский — подготовьте команду к международному бизнесу.",
    "biz.use2.title": "Техническое обучение",
    "biz.use2.desc": "Python, JavaScript, data science — держите инженеров на передовой.",
    "biz.use3.title": "Программы адаптации",
    "biz.use3.desc": "Ускорьте продуктивность новых сотрудников структурированным обучением.",
    "biz.contactTitle": "Готовы трансформировать навыки команды?",
    "biz.contactSub": "Получите индивидуальный план обучения для вашей организации.",
    "biz.contactBtn": "Начать",
    "biz.form.company": "Название компании",
    "biz.form.name": "Контактное лицо",
    "biz.form.email": "Эл. почта",
    "biz.form.phone": "Телефон",
    "biz.form.teamSize": "Размер команды",
    "biz.form.teamSizePlaceholder": "напр. 10-50 сотрудников",
    "biz.form.message": "Сообщение",
    "biz.form.messagePlaceholder": "Расскажите о ваших потребностях в обучении...",
    "biz.form.submit": "Отправить запрос",
    "biz.form.success": "Запрос успешно отправлен! Мы свяжемся с вами в ближайшее время.",
    "biz.form.error": "Что-то пошло не так. Попробуйте ещё раз.",

    // Become a Tutor
    "tutor.title": "Стать репетитором",
    "tutor.subtitle": "Делитесь опытом, устанавливайте свой график и зарабатывайте на своих условиях.",
    "tutor.cta": "Подать заявку",
    "tutor.ctaSub": "Бесплатная регистрация · Начните зарабатывать за 48 часов",
    "tutor.whyTitle": "Почему преподавать на LearnEazy?",
    "tutor.feat1.title": "Устанавливайте свои ставки",
    "tutor.feat1.desc": "Вы решаете, сколько брать. LearnEazy берёт небольшую комиссию.",
    "tutor.feat2.title": "Гибкий график",
    "tutor.feat2.desc": "Преподавайте когда удобно. Установите доступность и принимайте бронирования.",
    "tutor.feat3.title": "AI-класс",
    "tutor.feat3.desc": "Видео, доска, заметки и AI-аналитика — всё в одном месте.",
    "tutor.feat4.title": "Развивайте свой бренд",
    "tutor.feat4.desc": "Создавайте репутацию с отзывами и профессиональным профилем.",
    "tutor.feat5.title": "Безопасные платежи",
    "tutor.feat5.desc": "Получайте оплату через TBC PayGe или BOG Pay. Еженедельные выплаты.",
    "tutor.feat6.title": "Поддержка и сообщество",
    "tutor.feat6.desc": "Доступ к обучающим ресурсам и сообществу репетиторов.",
    "tutor.howTitle": "Как это работает",
    "tutor.step1.title": "Подайте заявку",
    "tutor.step1.desc": "Заполните короткую анкету с квалификацией и опытом преподавания.",
    "tutor.step2.title": "Пройдите верификацию",
    "tutor.step2.desc": "Наша команда рассмотрит заявку и проверит квалификацию за 48 часов.",
    "tutor.step3.title": "Начните преподавать",
    "tutor.step3.desc": "Настройте профиль, выберите предметы и ставки, начните принимать студентов.",
    "tutor.statsTitle": "Присоединяйтесь к нашему сообществу",
    "tutor.stat1": "Активных репетиторов",
    "tutor.stat2": "Сред. месячный доход",
    "tutor.stat3": "Удовлетворённость репетиторов",
    "tutor.stat4": "Доступных предметов",
    "tutor.reqTitle": "Что мы ищем",
    "tutor.req1": "Экспертиза в вашем предмете",
    "tutor.req2": "Сильные коммуникативные навыки",
    "tutor.req3": "Надёжное интернет-соединение",
    "tutor.req4": "Страсть к обучению студентов",
    "tutor.req5": "Минимум 2 года преподавательского или профессионального опыта",
    "tutor.readyTitle": "Готовы начать преподавать?",
    "tutor.readySub": "Присоединяйтесь к тысячам репетиторов. Подайте заявку сегодня — это бесплатно.",
    "tutor.readyBtn": "Начать заявку",
    "tutor.heroHeadline": "Зарабатывайте, обучая крупнейшее сообщество учеников по всему миру",
    "tutor.teachStudentsTitle": "Обучайте студентов из 180+ стран",
    "tutor.teachStudentsDesc": "Репетиторы LearnEazy обучают 800,000+ студентов по всему миру.",
    "tutor.pf1": "Постоянный поток новых студентов",
    "tutor.pf2": "Умный календарь",
    "tutor.pf3": "Интерактивный класс",
    "tutor.pf4": "Удобные способы оплаты",
    "tutor.pf5": "Вебинары профессионального развития",
    "tutor.pf6": "Поддерживающее сообщество репетиторов",
    "tutor.testimonialQuote": "LearnEazy позволил мне зарабатывать не выходя из дома!",
    "tutor.testimonialAuthor": "Нино С. · Репетитор английского",
    "tutor.faqTitle": "Часто задаваемые вопросы",
    "tutor.faq1.q": "Каких репетиторов ищет LearnEazy?",
    "tutor.faq1.a": "Конкретный сертификат или опыт преподавания не требуется! Мы приветствуем репетиторов, которые любят делиться знаниями и имеют отличные коммуникативные навыки.",
    "tutor.faq2.q": "Какой предмет я могу преподавать?",
    "tutor.faq2.a": "На LearnEazy более 100 предметов, включая языки, школьные и университетские предметы, хобби и искусство.",
    "tutor.faq3.q": "Как стать онлайн-репетитором на LearnEazy?",
    "tutor.faq3.a": "1. Укажите основную информацию о себе\n2. Загрузите фото\n3. Опишите свои сильные стороны\n4. Запишите короткое видео\n5. Выберите доступность",
    "tutor.faq4.q": "Как быстро подтвердить профиль?",
    "tutor.faq4.a": "Используйте настоящее фото, запишите короткое видео и опишите свои сильные стороны как репетитора.",
    "tutor.faq5.q": "Почему стоит преподавать на LearnEazy?",
    "tutor.faq5.a": "Потому что это просто и гибко! Зарабатывайте, делясь знаниями, получайте поток студентов, преподавайте когда и где хотите.",
    "tutor.faq6.q": "Бесплатно ли создание профиля?",
    "tutor.faq6.a": "Да. Создание профиля, доступ к студентам и инструментам бесплатно. Мы берём небольшую комиссию только за проведённые уроки.",
    "tutor.faq7.q": "Сколько я могу заработать?",
    "tutor.faq7.a": "Популярные репетиторы зарабатывают до $550 в неделю. Доход зависит от вашей ставки и количества уроков.",
    "tutor.apply.step": "Шаг",
    "tutor.apply.step1Title": "Личная информация",
    "tutor.apply.step1Desc": "Расскажите нам о себе.",
    "tutor.apply.step2Title": "Квалификация и опыт",
    "tutor.apply.step2Desc": "Поделитесь своим преподавательским опытом.",
    "tutor.apply.step3Title": "Предметы и ставки",
    "tutor.apply.step3Desc": "Выберите, что хотите преподавать, и установите цену.",
    "tutor.apply.step4Title": "Доступность и финальные детали",
    "tutor.apply.step4Desc": "Сообщите нам, когда вы можете преподавать.",
    "tutor.apply.firstName": "Имя",
    "tutor.apply.lastName": "Фамилия",
    "tutor.apply.email": "Эл. почта",
    "tutor.apply.phone": "Телефон",
    "tutor.apply.country": "Страна",
    "tutor.apply.experience": "Опыт преподавания",
    "tutor.apply.selectExp": "Выберите уровень опыта",
    "tutor.apply.education": "Образование",
    "tutor.apply.educationPlaceholder": "напр. Магистр педагогики",
    "tutor.apply.certifications": "Сертификаты",
    "tutor.apply.certPlaceholder": "напр. TESOL, IELTS",
    "tutor.apply.bio": "О себе",
    "tutor.apply.bioPlaceholder": "Опишите свой стиль преподавания...",
    "tutor.apply.subjects": "Предметы",
    "tutor.apply.rate": "Почасовая ставка",
    "tutor.apply.nativeLang": "Родной язык",
    "tutor.apply.otherLangs": "Другие языки",
    "tutor.apply.availability": "Еженедельная доступность",
    "tutor.apply.selectAvail": "Выберите доступность",
    "tutor.apply.timezone": "Часовой пояс",
    "tutor.apply.aboutTeaching": "Философия преподавания",
    "tutor.apply.aboutTeachingPlaceholder": "Опишите, как вы подходите к преподаванию...",
    "tutor.apply.terms": "Я согласен с Условиями обслуживания и подтверждаю точность предоставленной информации.",
    "tutor.apply.back": "Назад",
    "tutor.apply.next": "Продолжить",
    "tutor.apply.submit": "Отправить заявку",
    "tutor.apply.submitting": "Отправка...",
    "tutor.apply.error": "Что-то пошло не так. Попробуйте ещё раз.",
    "tutor.apply.successTitle": "Заявка отправлена!",
    "tutor.apply.successDesc": "Спасибо за заявку! Наша команда рассмотрит её и свяжется с вами в течение 48 часов.",
    "tutor.apply.backHome": "На главную",

    // Auth
    "auth.login": "Войти",
    "auth.loginDesc": "С возвращением! Войдите в свой аккаунт.",
    "auth.signup": "Регистрация",
    "auth.signupDesc": "Создайте аккаунт, чтобы начать.",
    "auth.email": "Эл. почта",
    "auth.password": "Пароль",
    "auth.displayName": "Имя",
    "auth.displayNamePlaceholder": "Ваше имя",
    "auth.forgotPassword": "Забыли пароль?",
    "auth.forgotDesc": "Введите email и мы отправим ссылку для сброса пароля.",
    "auth.sendResetLink": "Отправить ссылку",
    "auth.sending": "Отправка...",
    "auth.resetSent": "Проверьте почту — мы отправили ссылку для сброса пароля.",
    "auth.backToLogin": "Назад к входу",
    "auth.noAccount": "Нет аккаунта?",
    "auth.signupLink": "Зарегистрироваться",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.loginLink": "Войти",
    "auth.signingIn": "Вход...",
    "auth.creatingAccount": "Создание аккаунта...",
    "auth.error": "Ошибка",
    "auth.welcomeBack": "С возвращением!",
    "auth.checkEmail": "Проверьте почту",
    "auth.verifyEmail": "Мы отправили ссылку для подтверждения. Проверьте почту, чтобы активировать аккаунт.",
    "auth.passwordMin": "Пароль должен содержать минимум 6 символов.",
    "auth.newPassword": "Новый пароль",
    "auth.newPasswordDesc": "Введите новый пароль ниже.",
    "auth.updatePassword": "Обновить пароль",
    "auth.updating": "Обновление...",
    "auth.passwordUpdated": "Пароль успешно обновлён!",
    "auth.logout": "Выйти",
    "auth.dashboard": "Панель",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem("learneazy-lang");
    return (saved as Language) || "en";
  });

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("learneazy-lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
